### PR TITLE
fix(db-postgres): query unset relation

### LINKED ISSUE #4611: Postgres adapter does not find documents where relation is set or unset
### Link to reproduction

https://github.com/joas8211/payloadcms/tree/repro/postgres-unset-relation

### Describe the Bug

In a situation where documents are hierarchical and so have a parent relation, it's not possible to find root document that has no parent relation set. The problem occur with both `equals: null` or `exists: false` conditions. There's also problem with finding all sub-documents of any root using `not_equals: null` condition. This problem does not occur when using MongoDB adapter. 

### To Reproduce

Clone reproduction branch (see link to reproduction), setup development environment, and run tests with following command:
```
PAYLOAD_DATABASE=postgres pnpm test:int test/_community/int.spec.ts
```

### Payload Version

2.5.0

### Adapters and Plugins

db-postgres: 0.2.2

### PR DESCRIPTION
**Pull request by joas8211**
## Description

This PR improves PostgreSQL adapter by allowing to query documents based on unset relations using `equals: null` and `exists: false`. Also quering set relations is now allowed using `not_equals: null` in addition of `exists: true`.
 
Fixes #4611

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/db-postgres/src/queries/getTableColumnFromPath.ts [hunk 1]
```diff
@@ -317,21 +317,15 @@ export const getTableColumnFromPath = ({
...
+          condition: and(
+            eq((aliasTable || adapter.tables[rootTableName]).id, aliasRelationshipTable.parent),
+            like(aliasRelationshipTable.path, `${constraintPath}${field.name}`),
           ),
           table: aliasRelationshipTable,
         })
 
         selectFields[`${relationTableName}.path`] = aliasRelationshipTable.path
 
-        constraints.push({
```
Comment (DanRibbens) [inline packages/db-postgres/src/queries/getTableColumnFromPath.ts:329]: Why are we removing the path here?
The purpose of the path constraint is to make sure that the field being queried is matched. Consider if you had two relationship fields on one document, there would be no way to discern without the path.

**Review by DanRibbens — CHANGES_REQUESTED** [review]
Looks good. Just wondering about the removal of the path constraint.

File: packages/db-postgres/src/queries/getTableColumnFromPath.ts (hunk 1 above)
Comment (joas8211) [reply packages/db-postgres/src/queries/getTableColumnFromPath.ts:329]: It's moved into the join constraint above to avoid filtering out rows that doesn't have relations. If there would be no relations the joined colums will be null instead, allowing us to select rows with unset relation.

Comment (DanRibbens) [reply packages/db-postgres/src/queries/getTableColumnFromPath.ts:329]: Oh yes, I see that now. Thanks.

**Review by DanRibbens — APPROVED** [review]

**Comment by DanRibbens** [comment]
Thank you @joas8211 !

We will get it out in the next release 🎉
