### PR TITLE
Fix/admin thumbnail base64

### LINKED ISSUE #2325: Returning a base64 image from `adminThumbnail` is prevented by `absoluteURLPattern`
# Bug Report

I won't bother you with my uses, case TLDR; I save my small images as `base64` encoded string alongside the usual media collection data. I've made it work with hooks and such but I'm having problem with `adminThumbnail` which will try the `absoluteURLPattern`, which will fail obv and then proceed to prepend `serverURL`, removing this from configuration make it work but I do feel that it will break something else

## Steps to Reproduce

return any base64 string image to `adminThumbnail`

## Other Details

I can do an MR but I want to know first what do you think about this because I don't know the whole codebase and want to prevent adding more bugs elsewhere.

### PR DESCRIPTION
**Pull request by PatrikKozak**
## Description

Correctly returns thumbnail URL in `adminThumbnail` if returned image is of `base64`.

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: src/admin/hooks/useThumbnail.ts [hunk 1]
```diff
@@ -29,7 +30,7 @@ const useThumbnail = (collection: SanitizedCollectionConfig, doc: Record<string,
     if (typeof adminThumbnail === 'function') {
       const thumbnailURL = adminThumbnail({ doc });
 
-      if (absoluteURLPattern.test(thumbnailURL)) {
+      if (absoluteURLPattern.test(thumbnailURL) || isBase64Image(thumbnailURL)) {
```
Comment (jacobsfletch) [inline src/admin/hooks/useThumbnail.ts:33]: Instead of importing a function, use a regex pattern just like on line 6.

```
const absoluteURLPattern = new RegExp('^(?:[a-z]+:)?//', 'i');
const base64Pattern = new RegExp('your_pattern_here');
```

**Review by jacobsfletch — APPROVED** [review]
