### PR TITLE
fix: rest api with `?locale=*` doesn't return full localized data

### LINKED ISSUE #9712: REST API query using locale=* returns no localized fields at all
### Describe the Bug

This was working fine with Payload 2.x but Payload 3.x returns no localized fields values for locale=*. Switching to locale=all returned again all raw field values.

Example request:

`http://localhost:3000/cms/api/pages/64f20533c977b00e9b704ae8?locale=*&fallback-locale=none&depth=0
`
I had a look at the source code and '*' gets converted to 'all' normally. I would not find any obvious bugs.

### Link to the code that reproduces this issue

https://github.com/cbratschi/payload

### Reproduction Steps

Use REST API with locale=*.

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Binaries:
  Node: 22.9.0
  npm: 10.8.3
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  payload: 3.2.2
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:23 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6031
  Available memory (MB): 65536
  Available CPU cores: 16
```

### PR DESCRIPTION
**Pull request by r1tsuu**
Fixes https://github.com/payloadcms/payload/issues/9712

### CODE REVIEW

File: packages/payload/src/utilities/createPayloadRequest.ts [hunk 1]
```diff
@@ -78,11 +78,6 @@ export const createPayloadRequest = async ({
     })
 
     locale = locales.locale
-
-    // Override if query params are present, in order to respect HTTP method override
-    if (query.locale) {
-      locale = query.locale as string
-    }
```
Comment (r1tsuu) [inline packages/payload/src/utilities/createPayloadRequest.ts:85]: this check isn't needed anymore because we already do retrieve it from `searchParams.get('locale'`)` which is the same as now we create a new `Request` object in `handleEndpoints` when overriding

**Review by DanRibbens — APPROVED** [review]
