### PR TITLE
fix(ui): bulk upload losing state when adding additional files

### LINKED ISSUE #12945: Bulk upload loses state
### Describe the Bug

When bulk editing and adding additional files, existing files lose their state.

https://github.com/user-attachments/assets/2a87a6cc-a954-4a76-a564-4b0ac7ea00a5

### Link to the code that reproduces this issue

Shown in video

### Reproduction Steps

1. Open bulk upload
2. Add data to upload
3. Add additional upload
4. Go to first upload and see that data is missing

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

```text
V3
```

### PR DESCRIPTION
**Pull request by JarrodMFlesch**
Fixes #12945 

Fixes an issue where adding additional upload files would clear the state of the originally uploaded files.

### CODE REVIEW

File: packages/ui/src/elements/ShimmerEffect/index.tsx [hunk 1]
```diff
@@ -6,21 +6,29 @@ import './index.scss'
...
 }) => {
   return (
     <div
-      className="shimmer-effect"
+      className={['shimmer-effect', className].filter(Boolean).join(' ')}
       style={{
-        height: typeof height === 'number' ? `${height}px` : height,
-        width: typeof width === 'number' ? `${width}px` : width,
+        height: disableInlineStyles
+          ? undefined
```
Comment (DanRibbens) [inline packages/ui/src/elements/ShimmerEffect/index.tsx]: Do you need this double ternary here? `disableInlineStyles` has a default value of `false` from in the props.

**Review by DanRibbens — CHANGES_REQUESTED** [review]
Just one question.

File: packages/ui/src/elements/ShimmerEffect/index.tsx (hunk 1 above)
Comment (JarrodMFlesch) [reply packages/ui/src/elements/ShimmerEffect/index.tsx]: Updated with:
```js
height: !disableInlineStyles && (typeof height === 'number' ? `${height}px` : height),
width: !disableInlineStyles && (typeof width === 'number' ? `${width}px` : width),
```

**Review by PatrikKozak — APPROVED** [review]

**Review by DanRibbens — APPROVED** [review]
