### PR TITLE
fix: apply CORS response headers without `headersWithCors`

### LINKED ISSUE #10332: Improve CORS related docs
# Documentation Issue

Me and my team are implementing an e-commerce product with two separate instances between back-end and front-end, CORS started to become an issue with v2 and now with v3 I couldn't for the life of me figure out what was going wrong, the docs briefly mention at [Config Options](https://payloadcms.com/docs/configuration/overview#config-options) you have the possibility to enable CORS and CSRF but these doesn't seem to work out of the box with custom Endpoints. Also https://payloadcms.com/docs/configuration/overview#cors seems to be broken since it doesn't lead anywhere on the site.

After many hours of digging I decided to checkout the repo and search everywhere for usages of CORS and came across `headersWithCors` at [examples/multi-tenant/src/collections/Users/endpoints/externalUsersLogin.ts](https://github.com/payloadcms/payload/blob/main/examples/multi-tenant/src/collections/Users/endpoints/externalUsersLogin.ts) and finally these seem to have fixed the issue once and for all.

## Additional Details

If custom Endpoints are not part of the default cors handling by default that should be explicit on the related section of the docs and the alternate solution could be briefly mentioned with a link to a concrete example. I reckon not everyone is going to hit this issue but it's frustrating to not find this piece of info in an otherwise pristine documentation.

### PR DESCRIPTION
**Pull request by r1tsuu**
Fixes https://github.com/payloadcms/payload/issues/10332

Previously, the `cors` configuration wasn't respected for:
- Custom endpoints without using `headersWithCors` which as described in https://github.com/payloadcms/payload/issues/10332 is not documented.
- Some of our endpoints like `/payload-jobs/run` or from plugins due to missing `headersWithCors` - https://github.com/payloadcms/payload/blob/592f02b3bf2241854202dec99ceb0c66a3fbf771/packages/payload/src/queues/restEndpointRun.ts#L82-L88

In 2.0, you didn't need `headersWithCors` and I think it's expected to handle this logic by default.
This completely removes `headersWithCors` boilerplate from the all endpoints and instead, handles this logic at the end of `handleEndpoints` directly - https://github.com/payloadcms/payload/compare/fix/default-cors?expand=1#diff-82e97630068f9fc40256f3f46e06226215ab150d16012281810586b51b0cfd51

Also deprecates public export of `headersWithCors`

### CODE REVIEW

File: packages/payload/src/utilities/routeError.ts [hunk 1]
```diff
@@ -100,7 +94,7 @@ export const routeError = async ({
   }, Promise.resolve())
 
   return Response.json(response, {
-    headers: req.responseHeaders ? mergeHeaders(req.responseHeaders, headers) : headers,
+    // headers with req.responseHeaders are merged in handleEndpoints directly
```
Comment (DanRibbens) [inline packages/payload/src/utilities/routeError.ts:97]: probably don't need to keep this comment, WDYT?

**Review by DanRibbens — APPROVED** [review]
Looks good. I had one question.

**Comment by AaronClaes** [comment]
I noticed that this is both added and [reverted](https://github.com/payloadcms/payload/pull/10718) in the same release ([v3.19.0](https://github.com/payloadcms/payload/releases/tag/v3.19.0))

Is there a timeline for when this PR will be added back? 

This change feels like the expected behavior and `headersWithCors` should probably be mentioned in the docs if this PR isn't going to be added back anytime soon.
