### PR TITLE
fix: #1059

### LINKED ISSUE #1059: UI: Scroll issue with collapsible elements
# Bug Report

Any collapsible elements creates scroll issues on the interface. 

## Steps to Reproduce
1. Gets a page with collapsible elements
2. Collapse all elements
3. Reload the page
4. Expand all blocks (should be bigger than the viewport)
5. Scroll to the bottom

## Detailed Description

The problem seems to occur when first page render height is smaller or equal to a full viewport height (100vh). When expanding an element, the height of the page change but the interface keeps it's initial height `100%` of the `html`/`body`.

In my case : 
- The left sidebar start scrolling instead of sticking at the top
- The "Add block" popup gets an incorrect position blocking the user from selecting a block

https://user-images.githubusercontent.com/45725915/188281206-481e717e-dc25-4c26-9c6e-6361cd5aa777.mp4

### PR DESCRIPTION
**Pull request by jmikrut**
## Description

Fixes #1059 

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: src/admin/components/elements/Popup/index.tsx [hunk 1]
```diff
@@ -30,26 +28,29 @@ const Popup: React.FC<Props> = (props) => {
     boundingRef,
   } = props;
 
+  const { width: windowWidth, height: windowHeight } = useWindowInfo();
+  const [intersectionRef, intersectionEntry] = useIntersect({
+    threshold: 1,
```
Comment (Shednandez) [inline src/admin/components/elements/Popup/index.tsx:33]: request review and payment credits issued @ shednandez

0xf752EC3A9091Aa800561f5e232e7b0b326402215

**Review by Shednandez — COMMENTED** [review]
veiwed

File: src/admin/components/elements/Popup/index.tsx (hunk 1 above)
Comment (Shednandez) [reply src/admin/components/elements/Popup/index.tsx:33]: 0xf752EC3A9091Aa800561f5e232e7b0b326402215
