### PR TITLE
fix: adds null to non-required field unions

### LINKED ISSUE #3777: Generated TypeScript types do not include `null` on optional fields
### Link to reproduction

https://github.com/payloadcms/payload/blob/0f3b364e467092f5f996df3999dc9a739fa9264a/test/_community/payload-types.ts#L18-L24

### Describe the Bug

`generated:types` generates non-required fields as optional properties. This makes it impossible to update such a field to be absent using the local API, if `strictNullChecks` are enabled in tsconfig. This option is highly desirable as it catches many null/undefined related bugs at compile time rather than at runtime.

```ts
await payload.update({
  collection: 'posts',
  where: {},
  data: {
    text: null
  }
});
```
This is not allowed under [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks), because `text` is typed as `text?: string`.
Using `undefined` does not accomplish anything, as this is interpreted by Payload as "don't update this field". Even so using `undefined` would violate [`exactOptionalPropertyTypes`](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes), which is another very useful option to make TypeScript even more safe.

### To Reproduce

Attempt to set a non-required field to `null` using the local API with `strictNullChecks` enabled.

### Payload Version

2.0.11

### Adapters and Plugins

n/a

### PR DESCRIPTION
**Pull request by JarrodMFlesch**
## Description

Fixes https://github.com/payloadcms/payload/issues/3777

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

When a field is not required, append the `null` type to the generated type as a union. This PR also reduces looping in some places.

#### Before
```ts
// autogenerated payload-types.ts file
export interface Post {
  optionalText?: string;
  requiredText: string;
}
```

#### After
```ts
// autogenerated payload-types.ts file
export interface Post {
  optionalText?: string | null;
  requiredText: string;
}
```

This is a simplified case, but the nullability stretches across all applicable fields:
- text
- number
- upload
- relationship
- textarea
- code
- email
- date
- select
- radio
- point
- array
- blocks
- checkbox

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/payload/src/graphql/schema/withOperators.ts [hunk 1]
```diff
@@ -207,16 +207,12 @@ const defaults: DefaultsType = {
...
-              if (typeof option === 'string') {
-                return {
-                  ...values,
-                  [option]: {
-                    value: option,
-                  },
-                }
+              return {
+                ...values,
+                [formatName(option)]: {
```
Comment (DanRibbens) [inline packages/payload/src/graphql/schema/withOperators.ts:212]: We we'ren't formatting text options before?
Is this an unacaught bug or are we doing this somewhere else also?

File: packages/payload/src/utilities/configToJSONSchema.ts [hunk 2]
```diff
@@ -70,50 +80,45 @@ function fieldsToJSONSchema(
   }
   required: string[]
 } {
-  // required fields for a schema (could be for a nested schema)
-  const requiredFields = new Set<string>(
-    fields.filter(propertyIsRequired).map((field) => (fieldAffectsData(field) ? field.name : '')),
-  )
+  const requiredFieldNames = new Set<string>()
```
Comment (DanRibbens) [inline packages/payload/src/utilities/configToJSONSchema.ts:83]: Any reason to use a `Set` instead of keyed object for the field names?

We don't often use these and the syntax differences/cognitive load hasn't seemed worth it to me, just curious.

File: packages/payload/src/utilities/configToJSONSchema.ts [hunk 3]
```diff
@@ -60,6 +60,16 @@ function generateEntitySchemas(
   }
 }
 
+function withNullableType(
```
Comment (DanRibbens) [inline packages/payload/src/utilities/configToJSONSchema.ts:63]: this `withNullableType` function is missing some checks that our other `withNullableType` found here https://github.com/payloadcms/payload/blob/main/packages/payload/src/graphql/schema/withNullableType.ts is checking for: 
conditions, localized, access control.

Shouldn't they be the same conditions?

**Review by DanRibbens — CHANGES_REQUESTED** [review]
Looks good overall! I did have a few minor questions. I agree with the issue and the changes you made to address it.

Because we're opening up the types from up by adding nulls it can be considered a non-breaking change. I was really looking for situations where that wasn't true and saw none. :)

One more thing you should do before this gets merged is regenerate the graphql schema files in the test suites. That way the PR also shows how these changes impact the schema.

File: packages/payload/src/graphql/schema/withOperators.ts (hunk 1 above)
Comment (JarrodMFlesch) [reply packages/payload/src/graphql/schema/withOperators.ts:212]: It was an uncaught bug, we were doing it correctly for radio above: https://github.com/payloadcms/payload/pull/3870/files/b918b99f6f385ff61ca6b4fe396fd345b89e5547#diff-a9767f97c784c2103e2aca5a105cab436d3c8dc156ea64df53b0ea9a3ae120f8L166-L170

File: packages/payload/src/utilities/configToJSONSchema.ts (hunk 2 above)
Comment (JarrodMFlesch) [reply packages/payload/src/utilities/configToJSONSchema.ts:83]: It was a Set before and I just did not want to refactor the below. The nice thing about them is they don't store duplicative values.

File: packages/payload/src/utilities/configToJSONSchema.ts (hunk 3 above)
Comment (JarrodMFlesch) [reply packages/payload/src/utilities/configToJSONSchema.ts:63]: ooooo good catch, I can make this match that.

Comment (JarrodMFlesch) [reply packages/payload/src/utilities/configToJSONSchema.ts:63]: Hmm actually looking at this closer, I think we should leave it as is. If I change it to match the GraphQL one, we will generate much different types than we currently are. Take the `read` access control check in the GraphQL one for example, if we used that then a ton of fields that before were required will now be optional. 

I think it would be better to leave them as is for now and address this properly in the future by generating specific types for CRUD operations.

File: packages/payload/src/utilities/configToJSONSchema.ts (hunk 2 above)
Comment (DanRibbens) [reply packages/payload/src/utilities/configToJSONSchema.ts:83]: Oh right, I didn't see that we also had the Set before.

File: packages/payload/src/utilities/configToJSONSchema.ts (hunk 3 above)
Comment (DanRibbens) [reply packages/payload/src/utilities/configToJSONSchema.ts:63]: Yeah that makes sense with `read`. I'm not sure I agree for conditions though. Condition is not operation specific.

Comment (JarrodMFlesch) [reply packages/payload/src/utilities/configToJSONSchema.ts:71]: I made the changes in [this function](https://github.com/payloadcms/payload/pull/3870/files#diff-50cbef23ef608a8e1c9bad6cbf9b65822b206d2b4d618d6ff89455381c67ca06R14-R37)

I removed the read check from fields with fields because it felt odd that we were only targeting group fields with that condition, and again I think we should just improve types in the future.

**Review by DanRibbens — APPROVED** [review]

**Comment by silveltman** [comment]
Is there any way to manually disabled this?

I'm using a payload config to set variants for CVA (cva.style). I also auto-generate the props for my variants using's its VariantProps feture.

CVA's generated types do not accept null unfortunately.

**Comment by JarrodMFlesch** [comment]
@silveltman There is not a way to opt out of this. Have you asked the cva folks if they could provide a solution for your problem? Seems like something that library should handle.

**Comment by klapec** [comment]
@JarrodMFlesch when can a field be omitted from a payload's rest api response? I'm trying to understand the distinction between `null` and `undefined` when it comes to how payload stores data in mongo and how it produces a rest api response.
Suppose we have an `array` type field defined on a payload collection and it does not have a `defaultValue: []` set. Will payload respond with `field_name: []` or `field_name: null` or will the field be omitted from the response altogether?

**Comment by silveltman** [comment]
@klapec I don't know about the array example you gave, what I do know is that when you 'clear' a multiselect field, payload sets `null` instead of `undefined`

**Comment by TheDunco** [comment]
> Because we're opening up the types from up by adding nulls it can be considered a non-breaking change. I was really looking for situations where that wasn't true and saw none. :)

**@DanRibbens Would it be possible to explicitly call out large generated type changes like this in future release notes?**

Even though this is considered a non-breaking change for Payload, it lead to large diffs in my generated types file which is a breaking type change between my frontend and the CMS that I have to manually resolve for each case updated (because I normalize some of the Payload types in my FE). I've been advocating since before Payload switched to semantic versioning for large generated type changes to be called out explicitly in the release notes.

The reason for this being I've been having a hell of a time upgrading to the latest version of 2.x (2.4.0) because I was upgrading from 1.5.x. Due to this change not being explicitly called out I had to walk through updating each patch version to see where and why this was changing so I can figure out how best to resolve it. This would have been avoided if changes to the generated types were explicitly called out.

Loving Payload 2.x so far though!

**Comment by dgtls-dev** [comment]
Hey people, pretty new to payload but until now I must admit I really like it, exceptional work. 

I just run into this ticket because I didn't understand why null was added to the interfaces optional values.
The documentation in fact do not inform the user about it: https://payloadcms.com/docs/typescript/generating-types

image

From a personal perspective, I think the problem described by @silveltman doesn't affect just CVA. For instance I've my own block library and in every component I've some optional properties. _Typescriptely_ speaking, as also @TheDunco noticed, this would lead me to update all components that have optional fields and enhance their types. 

I understand that this is a no-way-back update, maybe updating the docs with some information about it could be a nice update and can help the paylaod user to find a strategy accordingly.

All the best
