### PR TITLE
fix(db-postgres): query using blockType

### LINKED ISSUE #3838: nested relationship field rest api request, incorrect results
### Link to reproduction

_No response_

### Describe the Bug

in a document structure where a relationship field is inside a block youre unable to filter on the relationship values.

### To Reproduce

in a document structure that looks like this in a collection called "mainpages":

```
{
  "id": "652d0963cb6c65326d040114",
  "title": "test title",
  "slug": "test-slug",
  "pageLayout": [
    {
      "relCategories": [
        {
          "id": "652e350fa7799c0880277631",
          "title": "Design",
          "slug": "design",
          "_status": "published",
          "createdAt": "2023-10-17T07:17:35.304Z",
          "updatedAt": "2023-10-23T13:25:53.190Z"
        }
      ],
      "id": "652d09383a16ac85e2daef23",
      "blockType": "projectPageBlock"
    }
  ],
  "_status": "published",
  "createdAt": "2023-10-16T09:58:59.477Z",
  "updatedAt": "2023-10-24T07:33:44.005Z"
}

```

relCategories has hasMany: true

then perform a query using the 'qs' library as follows:

```
  const query = {
    and: [
      {
        'pageLayout.blockType': {
          equals: 'projectPageBlock'
        }
      },
      {
        'pageLayout.relCategories.slug': {
            equals: 'design'
        }
      }
    ]
  };

  const stringifiedQuery = qs.stringify(
    {
      where: query
    },
    { addQueryPrefix: true }
  );
```

URL:  /api/mainpages${stringifiedQuery}

this yields no results, if i remove the pageLayout.relCategories.slug object part from the query it at least returns the correct documents that match the blocktype. but i cant seem to combine the query with the relationship field containing that slug. im unsure if this an error in the way im expressing the query or if its a bug.

### Payload Version

2.0.11

### Adapters and Plugins

_No response_

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

Fix #3838 

In MongoDB the blockType is easily queried on because it takes shape in the actual document saved. This PR matches the functionality for postgres by looking at the value of the query for blockTypes and adding joins and constraints to the query to make sure the path matches and exists in the appropriate block table.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: packages/db-postgres/src/queries/getTableColumnFromPath.ts [hunk 1]
```diff
@@ -307,9 +344,9 @@ export const getTableColumnFromPath = ({
             table: blockTableColumn.table,
           }
         }
-        if (pathSegments[1] === 'blockType') {
-          throw new APIError('Querying on blockType is not supported')
-        }
+        // if (pathSegments[1] === 'blockType') {
```
Comment (denolfe) [inline packages/db-postgres/src/queries/getTableColumnFromPath.ts:347]: Looks like these need to be cleaned up.

File: packages/db-postgres/src/queries/parseParams.ts [hunk 2]
```diff
@@ -63,11 +63,12 @@ export async function parseParams({
             where: condition,
           })
           if (builtConditions.length > 0) {
-            if (result) {
-              result = operatorMap[conditionOperator](result, ...builtConditions)
-            } else {
-              result = operatorMap[conditionOperator](...builtConditions)
-            }
+            // if (result) {
```
Comment (denolfe) [inline packages/db-postgres/src/queries/parseParams.ts:66]: Here too
