### PR TITLE
fix: query on id throws 500

### LINKED ISSUE #2568: RichText Internal Link autocomplete drop down filtration error
### Link to reproduction

https://github.com/jakehopking/elkli-and-hart/tree/dev

### Video of bug
https://user-images.githubusercontent.com/3432643/234507285-c17b489f-45eb-42fc-b329-35ebc3843245.mov

Try to input any character with the 'Internal Link' autocomplete dropdown input option, on any RichText field implementation on any collection / layout block.

P.S. @DanRibbens has access to the linked repo.

### Describe the Bug

- Causes the autocomplete box to fail. 
- Writes a 404 log to the browser console:
```
GET http://10.0.1.236:3000/payload/orders?where%5Band%5D%5B1%5D%5Borders%5D%5Blike%5D=h&limit=10&page=1&sort=orders&locale=en&depth=0 400 (Bad Request)
```
- Same error can be see in the browser's network tab:
```
Request URL: http://10.0.1.236:3000/payload/orders?where%5Band%5D%5B1%5D%5Borders%5D%5Blike%5D=h&limit=10&page=1&sort=orders&locale=en&depth=0
Request Method: GET
Status Code: 400 Bad Request
```

> **Note:** I do not have localisation enabled anywhere within the global or local configs.
> Therefore it's odd that `locale=en` is in this payload generated query 👈 

### UI in error state with console error
Screenshot 2023-04-25 at 16 14 45

### Payload Version

1.7.1

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

Fixes https://github.com/payloadcms/payload/issues/2568

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: src/mongoose/sanitizeQueryValue.ts [hunk 1]
```diff
@@ -22,10 +22,7 @@ export const sanitizeQueryValue = ({ ctx, field, path, operator, val, hasCustomI
     if (!hasCustomID) {
       const isValid = mongoose.Types.ObjectId.isValid(val);
 
-      formattedValue = new mongoose.Types.ObjectId(val);
-
       if (!isValid) {
-        ctx.errors.push({ path });
```
Comment (DanRibbens) [inline src/mongoose/sanitizeQueryValue.ts:28]: I'd like to talk through this change @jmikrut. If we are pushing errors here, then I think we need to do more formatting upfront. I think we go back to returning undefined and so the query can ignore it without any error.
