### PR TITLE
fix: ensure tab label and description are serializable

### LINKED ISSUE #10114: Assigning a label or description function to a tab causes runtime error
### Describe the Bug

Assigning a label function or a description function to a tab will cause a runtime error due to passing a function to a client component. 

### Link to the code that reproduces this issue

https://github.com/akhrarovsaid/payload/tree/repro/tab-desc-or-label-error

### Reproduction Steps

- Grab repro
- `pnpm dev _community`
- Observe error

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Payload 3.10.0
Next: 15.1.0
Node: 20+
```

### PR DESCRIPTION
**Pull request by akhrarovsaid**
### What?
This PR fixes an issue where assigning a label or description function to a tab would cause a runtime error due to passing a function to a client component.

### Why?
To prevent runtime errors when using non-static designations.

### How?
By properly evaluating label and description functions prior to assignment to their `clientTab` counterpart.

Fixes #10114

Before:
image

After:
image

### CODE REVIEW

File: packages/payload/src/fields/config/client.ts [hunk 1]
```diff
@@ -300,6 +300,12 @@ export const createClientField = ({
                 i18n,
                 importMap,
               })
+            } else if (key === 'label' || key === 'description') {
```
Comment (DanRibbens) [inline packages/payload/src/fields/config/client.ts:303]: Couldn't this be simplified?
```
 } else if ((key === 'label' || key === 'description') && typeof tab[key] === 'function') {
  clientTab[key] = content({ t: i18n.t })
} else {
  clientTab[key] = tab[key]
}
```

Comment (akhrarovsaid) [reply packages/payload/src/fields/config/client.ts]: You're absolutely right. Tunnel vision. I opted to put `tab[key]` into it's own variable since I didn't like either of:

```
// Concise but readability is poor
if (...) {
  clientTab[key] = tab[key]({ t: i18n.t })
}
```

Or

```
// More verbose and we don't reuse content anywhere
if (...) {
  const content = tab[key]
  clientTab[key] = content({ t: i18n.t })
}
```

**Review by DanRibbens — APPROVED** [review]
