### PR TITLE
fix: filtering joins in `where` by ID

### LINKED ISSUE #12768: Filtering on a join field in filterOptions crashes
### Describe the Bug

In my repro project I want to filter out the media files relevant to a master product.

[Here](https://github.com/JesperWe/join-filter/blob/44475416a0a08ecb8792d47b441c004f7b9d42b8/src/payload.config.ts#L61) is the relevant code, which uses a `join` field to filter.

This filter crashes with: 

```
POST /admin/collections/productmaster/1 500 in 36ms
 ⨯ [Error [APIError]: Cannot find field for path at undefined] 
{
  data: null,
  isOperational: true,
  isPublic: false,
  status: 500,
  digest: '1298757053',
  [cause]: null
}
```
The HTTP request looks ok to me:

```json
[
  {
    "name": "render-list",
    "args": {
      "allowCreate": true,
      "collectionSlug": "media",
      "disableBulkDelete": true,
      "disableBulkEdit": true,
      "disableQueryPresets": "$undefined",
      "drawerSlug": "list-drawer_1_«r1c»",
      "enableRowSelections": "$undefined",
      "overrideEntityVisibility": true,
      "query": {
        "where": {
          "used_by_product": {
            "in": [
              1,
              2
            ]
          },
          "id": {
            "not_in": []
          }
        }
      }
    }
  }
]
```
### Link to the code that reproduces this issue

https://github.com/JesperWe/join-filter.git

### Reproduction Steps

In the repro app:

1. Create a Product
2. Add a media file to Product
3. Create a Productmaster with a relation to the product
4. Attempt to add a hero image to the Productmaster
5. The selection UI does not appear as expected, error is reported on backend

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

```text
Binaries:
  Node: 20.11.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 10.11.1
Relevant Packages:
  payload: 3.42.0
  next: 15.3.0
  @payloadcms/email-nodemailer: 3.42.0
  @payloadcms/graphql: 3.42.0
  @payloadcms/next/utilities: 3.42.0
  @payloadcms/payload-cloud: 3.42.0
  @payloadcms/richtext-lexical: 3.42.0
  @payloadcms/translations: 3.42.0
  @payloadcms/ui/shared: 3.42.0
  react: 19.1.0
  react-dom: 19.1.0
```

### PR DESCRIPTION
**Pull request by r1tsuu**
Fixes https://github.com/payloadcms/payload/issues/12768

Example:
```
const found_1 = await payload.find({
  collection: 'categories',
  where: { 'relatedPosts.id': { equals: post.id } },
})
```
or
```
const found_2 = await payload.find({
  collection: 'categories',
  where: { relatedPosts: { equals: post.id } },
})
```

### CODE REVIEW

File: packages/payload/src/database/queryValidation/validateSearchParams.ts [hunk 1]
```diff
@@ -104,6 +104,12 @@ export async function validateSearchParam({
         return
       }
 
+      // where: { relatedPosts: { equals: 1}} -> { 'relatedPosts.id': { equals: 1}}
```
Comment (DanRibbens) [inline packages/payload/src/database/queryValidation/validateSearchParams.ts:107]: cleanup?

**Review by DanRibbens — CHANGES_REQUESTED** [review]
Good but one commented line appears to have snuck in.

File: packages/payload/src/database/queryValidation/validateSearchParams.ts (hunk 1 above)
Comment (r1tsuu) [reply packages/payload/src/database/queryValidation/validateSearchParams.ts:107]: this comment was intentional, indicates that `relatedPosts` is transformed to `relatedPosts.id` here
it's not a valid ts code

**Review by DanRibbens — APPROVED** [review]
