### PR TITLE
fix(plugin-seo): tabbedUI with email field causes duplicate field

### LINKED ISSUE #4902: DuplicateFieldName in user collection
### Link to reproduction

-

### Describe the Bug

When I declare a field that already exists in user collection to merge settings with mine the build process stop to report the following error:
`DuplicateFieldName: A field with the name 'email' was found multiple times on the same level. Field names must be unique.`
This way to extend the native fields worked with the previous version ("payload": "2.4.0") 

### To Reproduce

1. Add the user collection in the config

```ts
const Users: CollectionConfig = {
	slug: "users",
	auth: true,
	fields: [
		{
			name: "email",
			type: "email",
			label: "Email",
			access: {
				read: ({ req, id }) => {
					// Extend logic
					const isAdmin = accessUserWithRole(req.user, "admin");
					const isSelf = accessCurrentUser(req.user, id);
					return isAdmin || isSelf;
				},
			},
		}
	],
}
```

2. install dependencies `yarn install`
3. Execute the build `npm run build`
4. The build stop with the error

### Payload Version

"payload": "2.8.2",

### Adapters and Plugins

"@payloadcms/bundler-webpack": "1.0.6", 		"@payloadcms/db-mongodb": "1.3.2", 		"@payloadcms/plugin-cloud-storage": "1.1.1", 		"@payloadcms/plugin-form-builder": "1.2.0", 		"@payloadcms/plugin-nested-docs": "1.0.11", 		"@payloadcms/plugin-seo": "2.2.0", 		"@payloadcms/richtext-lexical": "0.5.2", 		"@payloadcms/richtext-slate": "1.3.1",

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

fixes #4902

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: packages/plugin-seo/src/index.ts [hunk 1]
```diff
@@ -99,17 +99,29 @@ const seo =
 
           if (isEnabled) {
             if (pluginConfig?.tabbedUI) {
+              //
```
Comment (denolfe) [inline packages/plugin-seo/src/index.ts:102]: Blank comment?
