### PR TITLE
fix(next): properly closes `leave-without-saving` modal after navigating from `Leave anyway` button

### LINKED ISSUE #7648: .pyaload__modal-container is not hidden when you confirm leaving page from the Leaving without saving modal
### Link to reproduction

_No response_

### Payload Version

3.0.0-beta-77

### Node Version

20.15.1

### Next.js Version

15.0.0-canary.104

### Describe the Bug

The payload__modal-contaier is not hidden when you confirm Leaving the page without saving.

### Reproduction Steps

1. Edit an item
2. Exit the page
3. Confirm leaving the page from the `Leave without saving` modal
modal enter done 1
4. The `#leave-without-saving` dialog is removed from DOM but the container still has the `.payload__modal-container-enterDone` class
modal enter done
5. After you click on the screen, the modal is hidden. The `.payload__modal-container-exitDone` is attached. But it should be added when you confirm leaving the edit page.
modal exit done

### Adapters and Plugins

_No response_

### PR DESCRIPTION
**Pull request by PatrikKozak**
## Description

Fixes #7648 

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: packages/next/src/elements/LeaveWithoutSaving/usePreventLeave.tsx [hunk 1]
```diff
@@ -1,6 +1,7 @@
 // Credit: @Taiki92777
 //    - Source: https://github.com/vercel/next.js/discussions/32231#discussioncomment-7284386
 // Credit: `react-use` maintainers
+import { useModal } from '@payloadcms/ui'
```
Comment (jacobsfletch) [inline packages/next/src/elements/LeaveWithoutSaving/usePreventLeave.tsx:4]: This hook should not rely on useModal whatsoever, if you need to performa. side-effect, pass in your callback function as a prop.

**Review by jacobsfletch — APPROVED** [review]
