### PR TITLE
templates: fix issue with populateAuthors hook breaking live-preview on website template

### LINKED ISSUE #11468: Live Preview breaks with populateAuthors hook
### Describe the Bug

Live Preview breaks on the website template if authors are set.  Seems to be due to hooks `afterRead: [populateAuthors]`

Disabling the hooks works correctly, and from what I have observed, the doc.authors is a Buffer type in src/collections/Posts/hooks/populateAuthors.ts, which seems to cause the issue.

I also tested 3.24.0 and it has the same issue.

### Link to the code that reproduces this issue

pnpx create-payload-app@latest -t website

### Reproduction Steps

1. npx create-payload-app@latest with website template
2. open network tab
3. create a post without an author
4. open livepreview
5. type content in body
6. observe that refreshes occur
7. add author
8. type content in body
9. observe patch 404 to the article and refreshes do not occur

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Binaries:
  Node: 22.14.0
  npm: 10.9.2
  Yarn: N/A
  pnpm: 10.3.0
Relevant Packages:
  payload: 3.25.0
  next: 15.2.0
  @payloadcms/db-mongodb: 3.25.0
  @payloadcms/email-nodemailer: 3.25.0
  @payloadcms/graphql: 3.25.0
  @payloadcms/live-preview: 3.25.0
  @payloadcms/live-preview-react: 3.25.0
  @payloadcms/next/utilities: 3.25.0
  @payloadcms/payload-cloud: 3.25.0
  @payloadcms/plugin-form-builder: 3.25.0
  @payloadcms/plugin-nested-docs: 3.25.0
  @payloadcms/plugin-redirects: 3.25.0
  @payloadcms/plugin-search: 3.25.0
  @payloadcms/plugin-seo: 3.25.0
  @payloadcms/richtext-lexical: 3.25.0
  @payloadcms/translations: 3.25.0
  @payloadcms/ui/shared: 3.25.0
  react: 19.0.0
  react-dom: 19.0.0
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:24 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 12
```

### PR DESCRIPTION
**Pull request by paulpopus**
Fixes https://github.com/payloadcms/payload/issues/11468

The populateAuthors hook could break live preview if it returned a notFound error as we didn't catch these properly

### CODE REVIEW

File: templates/website/src/collections/Posts/hooks/populateAuthors.ts [hunk 1]
```diff
@@ -6,26 +6,31 @@ import { User } from 'src/payload-types'
...
+          depth: 0,
+        })
 
-      if (authorDoc) {
-        authorDocs.push(authorDoc)
+        if (authorDoc) {
+          authorDocs.push(authorDoc)
+        }
+
+        if (authorDocs.length) {
```
Comment (PatrikKozak) [inline templates/website/src/collections/Posts/hooks/populateAuthors.ts:24]: @paulpopus I prefer being more explicit here with `authorDocs.length > 0` but functionality is the same so up to you.

File: templates/with-vercel-website/src/collections/Posts/hooks/populateAuthors.ts [hunk 2]
```diff
@@ -6,26 +6,31 @@ import { User } from 'src/payload-types'
...
+          depth: 0,
+        })
 
-      if (authorDoc) {
-        authorDocs.push(authorDoc)
+        if (authorDoc) {
+          authorDocs.push(authorDoc)
+        }
+
+        if (authorDocs.length) {
```
Comment (PatrikKozak) [inline templates/with-vercel-website/src/collections/Posts/hooks/populateAuthors.ts:24]: Same comment as above

**Review by PatrikKozak — APPROVED** [review]
