### PR TITLE
fix: use consistent empty state styling between list and folder views

### LINKED ISSUE #15524: Empty list and folder view differ completely in styling
### Describe the Bug.

Opening a new issue as requested in #15484.

The empty views for both list and folder view wildly differ in styling. For consistency in user experience it would be great if they’d match.

Image

Image

Possible solution:

Image

### Reproduction Steps

Add a collection
Enable folders
View list vs folder view when collection is empty

### Environment Info

```text
Binaries:
  Node: 22.21.1
  npm: 10.9.4
  Yarn: 1.22.19
  pnpm: 10.24.0
Relevant Packages:
  payload: 3.71.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.6.0: Wed Nov  5 21:33:58 PST 2025; root:xnu-11417.140.69.705.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
```

### PR DESCRIPTION
**Pull request by AhmadYasser1**
### What?

Uses the shared `NoListResults` component in the list view empty state, matching the styling already used by the folder and browse-by-folder views.

### Why?

The empty state for the list view (left-aligned, no border) looks completely different from the folder view empty state (centered, dashed border). This inconsistency was reported in #15524.

### How?

- Replaced the inline `collection-list__no-results` div in `DefaultListView` with the existing `NoListResults` component from `elements/NoListResults`
- Removed the now-unused `&__no-results` SCSS block from `List/index.scss`
- Updated e2e test selectors from `.collection-list__no-results` to `.no-results`

#### Before
Screenshot 2026-02-13 at 1 48 40 PM

Screenshot 2026-02-13 at 1 48 48 PM

#### After
Screenshot 2026-02-17 at 3 34 37 PM

Screenshot 2026-02-17 at 3 34 43 PM

Fixes #15524

### CODE REVIEW

**Comment by PatrikKozak** [comment]
Hey @AhmadYasser1!

Thanks for opening this PR, I pulled it down and everything was looking good but I decided to take the updated empty state styling a bit further - I think it looks a bit cleaner now.

You can see the updated styles in the before & after images I added in the PR description.

Once CI passes, we'll get this merged.

Thanks again!

File: packages/translations/src/languages/de.ts [hunk 1]
```diff
@@ -376,6 +376,10 @@ export const deTranslations: DefaultTranslationsObject = {
     noOptions: 'Keine Optionen',
     noResults:
       'Keine {{label}} gefunden. Entweder es existieren keine {{label}} oder es gibt keine Übereinstimmung zu den von dir verwendeten Filtern.',
+    noResultsDescription:
+      'Entweder existieren keine oder keine entsprechen den von Ihnen oben angegebenen Filtern.',
+    noResultsFound:
+      'Respektieren Sie die Bedeutung des Originaltextes im Kontext von Payload. Hier ist eine Liste gängiger Payload-Begriffe, die sehr spezifische Bedeutungen haben:\n    - Sammlung: Eine Sammlung ist eine Gruppe von Dokumenten, die eine gemeinsame Struktur und einen gemeinsamen Zweck teilen. Sammlungen werden verwendet, um Inhalte in Payload zu organisieren und zu verwalten.\n    - Feld: Ein Feld ist ein spezifisches Stück Daten in einem Dokument einer Sammlung. Felder definieren die Struktur und den Datentyp, der in einem Dokument gespeichert werden kann.\n    - Dokument: Ein Dok',
```
Comment (jhb-dev) [inline packages/translations/src/languages/de.ts]: It looks like a part of the translation prompt sneaked in here. (I also noticed this issue when while working on  https://github.com/payloadcms/payload/pull/14439)

The german translation should be something like 'Keine Ergebnisse gefunden' here.

Comment (PatrikKozak) [reply packages/translations/src/languages/de.ts]: @jhb-dev Good catch! That is odd, I will fix this.

**Comment by AhmadYasser1** [comment]
Thanks @PatrikKozak and @jhb-dev!

Since CI passed, are we good to merge?

**Review by PatrikKozak — APPROVED** [review]
