### PR TITLE
fix(ui): unique ids for nested rows on row duplicate to prevent errors with postgres

### LINKED ISSUE #8784: Duplicating blocks with blocks errors
### Describe the Bug

You can have duplicate IDs for subblocks after duplicating a parent block, resulting in a duplicate ID error from postgres.

### Link to the code that reproduces this issue

pnpm dev fields

### Reproduction Steps

From the monorepo on beta,

1. pnpm dev fields
2. navigate to blocks /admin/collection/block-fields
3. duplicate the top "Sub-Block demostration" block
4. Save
5. Error: The following field is invalid: id

In the form state in duplicate will have multiple of the same ID for `subBlocks.0.id` within the rows, for example: 
```
        "subBlocks.0.id": {
            "errorPaths": [],
            "initialValue": "67127e767e97675fcceae274",
            "passesCondition": true,
            "valid": true,
            "value": "67127e767e97675fcceae274"
        },
```

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

payload 3.0.0-beta.114
db-postgres

### PR DESCRIPTION
**Pull request by r1tsuu**
Fixes https://github.com/payloadcms/payload/issues/8784

This works for any deep level, both arrays and blocks.

### CODE REVIEW

File: packages/ui/src/forms/Form/fieldReducer.ts [hunk 1]
```diff
@@ -263,6 +263,15 @@ export function fieldReducer(state: FormState, action: FieldAction): FormState {
         duplicateRowState.id.initialValue = new ObjectId().toHexString()
       }
 
+      for (const key of Object.keys(duplicateRowState).filter((key) => key.endsWith('.id'))) {
+        const idState = duplicateRowState[key]
+
+        if (idState && typeof idState.value === 'string' && ObjectId.isValid(idState.value)) {
+          duplicateRowState[key].value = new ObjectId().toHexString()
+          duplicateRowState[key].initialValue = new ObjectId().toHexString()
```
Comment (DanRibbens) [inline packages/ui/src/forms/Form/fieldReducer.ts:271]: There is likely no observable difference, but shouldn't these variables be assigned the same value?

**Review by DanRibbens — CHANGES_REQUESTED** [review]
It would be a quick e2e test to add considering we already have the config in place to support it.

In test/fields/e2e.spec.ts
Go to create block-fields
Duplicate the first block with sub blocks
Save and assert

This assumes we run e2e using postgres or SQLite which we don't currently in CI but we should reconsider that. For now running tests locally is good.

File: packages/ui/src/forms/Form/fieldReducer.ts (hunk 1 above)
Comment (r1tsuu) [reply packages/ui/src/forms/Form/fieldReducer.ts:271]: I had the same question here
https://github.com/payloadcms/payload/blob/ef8a5b1f3e94a4d12b96cee226ff0857cb33e887/packages/ui/src/forms/Form/fieldReducer.ts#L260-L264
So I just did how it was there

Comment (DanRibbens) [reply packages/ui/src/forms/Form/fieldReducer.ts:271]: Should be fine then. Seems odd to me, but it probably can't hurt anything!

**Review by DanRibbens — APPROVED** [review]
