### PR TITLE
fix(plugin-mcp): resolve union type fields failing in update tool

### LINKED ISSUE #14942: [MCP Plugin]: Unable to use update tool on fields with union type
### Describe the Bug

In MCP Plugin, the built-in `update` tool is not able to update top level fields with union type.

Example: With built-in `id` field which has union type:
Image

Example: With a custom top level field which has union type:
Image

Interestingly the nested fields with union type are updating fine.

### Link to the code that reproduces this issue

Reproduction steps given below

### Reproduction Steps

Method 1:
Use built-in update tool to update a post using its `id` (not using `where` clause).

Method 2:
Create a top level text field (non-required field). Its union type will be `string | null`. Try to update this field using the update tool.

### Which area(s) are affected?

plugin: mcp

### Environment Info

```text
Binaries:
  Node: 22.13.0
  npm: 10.9.2
  Yarn: 1.22.19
  pnpm: 9.15.1
Relevant Packages:
  payload: 3.68.5
  next: 15.5.9
  @payloadcms/db-postgres: 3.68.5
  @payloadcms/drizzle: 3.68.5
  @payloadcms/graphql: 3.68.5
  @payloadcms/live-preview: 3.68.5
  @payloadcms/live-preview-react: 3.68.5
  @payloadcms/next/utilities: 3.68.5
  @payloadcms/plugin-cloud-storage: 3.68.5
  @payloadcms/plugin-mcp: 3.68.5
  @payloadcms/plugin-redirects: 3.68.5
  @payloadcms/plugin-search: 3.68.5
  @payloadcms/plugin-seo: 3.68.5
  @payloadcms/richtext-lexical: 3.68.5
  @payloadcms/storage-s3: 3.68.5
  @payloadcms/translations: 3.68.5
  @payloadcms/ui/shared: 3.68.5
  react: 19.1.0
  react-dom: 19.1.0
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 25.1.0: Mon Oct 20 19:33:36 PDT 2025; root:xnu-12377.41.6~2/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
```

### PR DESCRIPTION
**Pull request by kendelljoseph**
`json-schema-to-zod` converts JSON Schema `oneOf` into `z.any().superRefine(...)`, whose `z.any()` base causes `zodToJsonSchema` to emit `{}` and lose all type information in MCP tool input schemas. 

- Fix by removing `$ref` options from `oneOf` entirely (only ID types needed for create/update) and converting remaining `oneOf` to `anyOf`, which produces clean `z.union([...])` validators.

- Also refactors schema conversion utilities into `utils/schemaConversion/` with dedicated modules for sanitization, relationship simplification, and point field transformation.

Fixes #14942

### CODE REVIEW

File: packages/plugin-mcp/src/utils/schemaConversion/convertCollectionSchemaToZod.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+import { simplifyRelationshipFields } from './simplifyRelationshipFields.js'
+import { transformPointFieldsForMCP } from './transformPointFields.js'
+
+export const convertCollectionSchemaToZod = (schema: JSONSchema4) => {
+  // Clone to avoid mutating the original schema (used elsewhere for tool listing)
+  const schemaClone = JSON.parse(JSON.stringify(schema)) as JSONSchema4
+
+  const sanitized = sanitizeJsonSchema(schemaClone)
+  const pointTransformed = transformPointFieldsForMCP(sanitized)
+  const simplifiedSchema = simplifyRelationshipFields(pointTransformed)
```
Comment (kendelljoseph) [inline packages/plugin-mcp/src/utils/schemaConversion/convertCollectionSchemaToZod.ts:17]: This file was moved (refactor)

There are no other changes to this file other than using the imported `simplifyRelationshipFields`.

File: packages/plugin-mcp/src/utils/schemaConversion/sanitizeJsonSchema.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
+import type { JSONSchema4 } from 'json-schema'
+
+/**
+ * Removes internal Payload properties (id, createdAt, updatedAt) from a
+ * JSON Schema so they don't appear in the generated Zod validation schema.
+ * Also strips `id` from the `required` array when present.
+ */
+export function sanitizeJsonSchema(schema: JSONSchema4): JSONSchema4 {
```
Comment (kendelljoseph) [inline packages/plugin-mcp/src/utils/schemaConversion/sanitizeJsonSchema.ts:8]: reactor: This performs the same sanitization as before.

File: packages/plugin-mcp/src/utils/schemaConversion/simplifyRelationshipFields.ts [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+  }
+
+  const processed = { ...schema }
+
+  if (Array.isArray(processed.oneOf)) {
+    const hasRef = processed.oneOf.some(
+      (option) => option && typeof option === 'object' && '$ref' in option,
+    )
+
+    if (hasRef) {
```
Comment (kendelljoseph) [inline packages/plugin-mcp/src/utils/schemaConversion/simplifyRelationshipFields.ts:32]: `hasRef` is the trigger that we look for to determine how to use `oneOf` or `anyOf`.

File: test/plugin-mcp/int.spec.ts [hunk 4]
```diff
@@ -316,7 +316,11 @@ describe('@payloadcms/plugin-mcp', () => {
         'The content of the post',
       )
       expect(json.result.tools[1].inputSchema.properties.author).toBeDefined()
-      expect(json.result.tools[1].inputSchema.properties.author.type).toBe(undefined)
+      expect(json.result.tools[1].inputSchema.properties.author.type).toHaveLength(2)
```
Comment (kendelljoseph) [inline test/plugin-mcp/int.spec.ts:319]: Supporting unions means we now have a property type here.

**Review by DanRibbens — APPROVED** [review]
This looks good! I'm just waiting on the CI to rerun.
