### PR TITLE
fix: prevent storing duplicate user preferences

### LINKED ISSUE #3678: Duplicating record under payload-preferences
### Link to reproduction

N/A

### To Reproduce

Refreshing the collection listing page, clicking on the hamburger menu, or collapsing/expanding the Collections/Globals accordion

### Describe the Bug

Duplicate record of payload-preferences being created every time refreshing the collection listing page, clicking on the hamburger menu, or collapsing/expanding the Collections/Globals accordion

Uploading Screen_Recording_2023-10-13_at_21.03.06.mov…

### Payload Version

2.0.7

### Adapters and Plugins

_No response_

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

fixes #3678
In addition to fixing it I also optimized the number of backend calls made by the frontend when updating multiple properties under the same key. A new optional `merge` flag was added to setPreferences to tell the provider to add properties to an existing key without overwriting and batch updates into one POST for each re-render.

I'm unsure how to to best write a test for this.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: packages/payload/src/admin/components/utilities/Preferences/index.tsx [hunk 1]
```diff
@@ -65,14 +67,57 @@ export const PreferencesProvider: React.FC<{ children?: React.ReactNode }> = ({
...
+        }
+      } else {
+        if (newValue === currentPreference) {
+          return
+        }
+        pendingUpdate.current[key] = newValue
+      }
+
+      const updatePreference = async () => {
+        if (isDeepEqual(pendingUpdate.current[key], preferencesRef.current[key])) {
```
Comment (JarrodMFlesch) [inline packages/payload/src/admin/components/utilities/Preferences/index.tsx:103]: Could use currentPreference here instead of preferencesRef.current[key]

File: packages/payload/src/admin/components/utilities/Preferences/index.tsx [hunk 2]
```diff
@@ -65,14 +67,57 @@ export const PreferencesProvider: React.FC<{ children?: React.ReactNode }> = ({
...
+
+        await requests.post(
+          `${serverURL}${api}/payload-preferences/${key}`,
+          requestOptions(preferencesRef.current[key], i18n.language),
+        )
+        delete pendingUpdate.current[key]
+      }
+
+      // use timeout to allow multiple changes of different values using the same key in one request
+      setTimeout(() => {
```
Comment (JarrodMFlesch) [inline packages/payload/src/admin/components/utilities/Preferences/index.tsx:116]: Should we add a time to the timeout? say 50ms? Makes it a bit more readable imo

File: packages/payload/src/admin/components/utilities/Preferences/index.tsx [hunk 3]
```diff
@@ -7,7 +8,7 @@ import { useConfig } from '../Config'
 
 type PreferencesContext = {
   getPreference: <T = any>(key: string) => Promise<T> | T
-  setPreference: <T = any>(key: string, value: T) => Promise<void>
+  setPreference: <T = any>(key: string, value: T, merge?: boolean) => Promise<void>
```
Comment (JarrodMFlesch) [inline packages/payload/src/admin/components/utilities/Preferences/index.tsx:11]: Should we change `merge` to `batch`?

File: packages/payload/src/admin/components/utilities/Preferences/index.tsx [hunk 4]
```diff
@@ -65,14 +67,57 @@ export const PreferencesProvider: React.FC<{ children?: React.ReactNode }> = ({
   )
 
   const setPreference = useCallback(
-    async (key: string, value: unknown): Promise<void> => {
-      preferencesRef.current[key] = value
-      await requests.post(
-        `${serverURL}${api}/payload-preferences/${key}`,
-        requestOptions(value, i18n.language),
-      )
+    async (key: string, value: unknown, merge = false): Promise<void> => {
```
Comment (JarrodMFlesch) [inline packages/payload/src/admin/components/utilities/Preferences/index.tsx:70]: Some comments might be helpful with all the if statements in here

**Review by JarrodMFlesch — CHANGES_REQUESTED** [review]
Overall looks good, just a couple small things I noted.

File: packages/payload/src/admin/components/utilities/Preferences/index.tsx (hunk 3 above)
Comment (DanRibbens) [reply packages/payload/src/admin/components/utilities/Preferences/index.tsx:16]: I left it `merge` since the flag is set to change the behaviour of what is being stored. The batching part is just a performance enhancement that you don't really need to know about when writing code that calls this function.

File: packages/payload/src/admin/components/utilities/Preferences/index.tsx (hunk 4 above)
Comment (DanRibbens) [reply packages/payload/src/admin/components/utilities/Preferences/index.tsx:75]: I commented up top in the PreferencesContext type.

File: packages/payload/src/admin/components/utilities/Preferences/index.tsx (hunk 1 above)
Comment (DanRibbens) [reply packages/payload/src/admin/components/utilities/Preferences/index.tsx:112]: I tried `currentPreference` but it actually needs to compare the most updated value directly on context or it would still send multiple requests here since we aren't reassigning `currentPreference` also.

File: packages/payload/src/admin/components/utilities/Preferences/index.tsx (hunk 2 above)
Comment (DanRibbens) [reply packages/payload/src/admin/components/utilities/Preferences/index.tsx:127]: This could break e2e testing to add a ms timeout. It does look odd, but given the comments I think it is okay to leave it out.

**Review by JarrodMFlesch — APPROVED** [review]
