### PR TITLE
fix(next): clear bfcache on forward/back

### LINKED ISSUE #12914: Back button loads outdated document after save
### Describe the Bug

When editing and saving a document in the Payload CMS admin panel, then navigating to a different page and returning via the browser's back button, the previously saved state is not reflected. Instead, the editor shows the old state of the document — the one before the latest save. If a user unknowingly makes changes and hits "Save" again, all recent updates will be overwritten by the outdated version. This behavior leads to accidental data loss. I experienced this several times, unintentionally overwriting previously updated content.

This issue occurs by default — no customizations have been made. It can be reproduced using the unmodified Payload website template.

### Link to the code that reproduces this issue

https://github.com/MarvinVrdoljak/payload-bug-report-3

### Reproduction Steps

1. Go to the admin panel and open a document for editing.
2. Make changes and click Save.
3. Navigate to a different route.
4. Click the browser’s back button to return to the previous document.
5. Observe: the editor displays the outdated version of the document (prior to the last save).
6. If you now hit Save, this outdated version will overwrite your latest changes.

https://github.com/user-attachments/assets/bdcc543b-be1f-4337-87af-b3468aaab355

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Binaries:
  Node: 22.14.0
  npm: 10.9.2
  Yarn: N/A
  pnpm: 10.10.0
Relevant Packages:
  payload: 3.43.0
  next: 15.3.0
  @payloadcms/db-mongodb: 3.43.0
  @payloadcms/email-nodemailer: 3.43.0
  @payloadcms/graphql: 3.43.0
  @payloadcms/live-preview: 3.43.0
  @payloadcms/live-preview-react: 3.43.0
  @payloadcms/next/utilities: 3.43.0
  @payloadcms/payload-cloud: 3.43.0
  @payloadcms/plugin-form-builder: 3.43.0
  @payloadcms/plugin-nested-docs: 3.43.0
  @payloadcms/plugin-redirects: 3.43.0
  @payloadcms/plugin-search: 3.43.0
  @payloadcms/plugin-seo: 3.43.0
  @payloadcms/richtext-lexical: 3.43.0
  @payloadcms/translations: 3.43.0
  @payloadcms/ui/shared: 3.43.0
  react: 19.1.0
  react-dom: 19.1.0
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Tue Nov 5 00:21:55 UTC 2024
  Available memory (MB): 15672
  Available CPU cores: 22
```

### PR DESCRIPTION
**Pull request by jacobsfletch**
Fixes #12914.

Using the forward/back browser navigation shows stale data from the previous visit.

For example:
1. Visit the list view, imagine a document with a title of "123"
2. Navigate to that document, update the title to "456"
3. Press the "back" button in the browser
4. Page incorrectly shows "123"
5. Press the "forward" button in the browser
6. Page incorrectly shows "123"

This is because Next.js caches those pages in memory in their [Client-side Router Cache](https://nextjs.org/docs/app/guides/caching#client-side-router-cache). This enables instant loads during forward and back navigation by restoring the previously cached response instead of making a new request—which also happens to be our exact problem. This bfcache-like behavior is not able to be opted out of, even if the page requires authentication, etc.

The [hopefully temporary] fix is to force the router to make a new request on forward/back navigation. We can do this by listening to the popstate event and calling `router.refresh()`. This does create a flash of stale content, however, because the refresh takes place _after_ the cache was restored. While not wonderful, this is targeted to specifically the forward/back events, and it's technically not duplicative as the restored cache never made a request in the first place.

Without native support, I'm not sure how else we'd achieve this, as there's not way to invalidate the list view from a deeply nested document drawer, for example.

Before:

https://github.com/user-attachments/assets/751b33b2-1926-47d2-acba-b1d47df06a6d

After:

https://github.com/user-attachments/assets/fe71938a-5c64-4756-a2c7-45dced4fcaaa

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1211454879207837

### CODE REVIEW

File: packages/ui/src/providers/RouteCache/index.tsx [hunk 1]
```diff
@@ -19,13 +19,29 @@ export const RouteCache: React.FC<{ cachingEnabled?: boolean; children: React.Re
...
+      window.removeEventListener('popstate', handlePopState)
+    }
+  }, [router])
+
+  useEffect(() => {
+    if (cachingEnabled || clearAfterPathnameChange.current) {
+      clearAfterPathnameChange.current = false
       clearRouteCache()
     }
   }, [pathname, clearRouteCache, cachingEnabled])
```
Comment (AlessioGr) [inline packages/ui/src/providers/RouteCache/index.tsx]: I think this is a good candidate for `useEffectEvent` to make sure this runs more predictably and only if pathname changes

Comment (jacobsfletch) [reply packages/ui/src/providers/RouteCache/index.tsx]: This ref is necessary to flag the effect _on the next render cycle_, only after pathname changes. Basically popstate fires → pathname changes → safe to refresh the router. I'm not sure how `useEffectEvent` would avoid this because the effect already only ever runs when pathname changes.

**Review by AlessioGr — DISMISSED** [review]

**Review by AlessioGr — APPROVED** [review]
