### PR TITLE
fix:Allow a custom ID field to be nested inside unnamed tabs and rows

### LINKED ISSUE #4546: Setting a custom ID field inside a tab breaks the ability to set a custom ID for the collection
Reproduction: https://github.com/GeorgeHulpoi/payload-seo-bug

1. Create a collection having a custom id.
2. Add this collection to seo plugin
3. Set tabbedUI equal with true.

From now, the id is no longer working, is using the ObjectId + the custom id.

### LINKED ISSUE #4628: Field name `id` not honored inside of `row` field
### Link to reproduction

_No response_

### Describe the Bug

If a field named `id` is inside of a `row` field, it is not honored, and a `_id` is created in addition to a `id` property in the database.

### To Reproduce

This configuration does not respect the `id` field name as the ID of the collection, with any saved documents having the `id` value in addition to an `_id` of ObjectId.   (Note: this is on Mongo - I did not test this on Postgres)

```typescript
export const Tags: CollectionConfig = {
  slug: 'tags',
  fields: [
    { type: 'row', fields: [
      { name: 'id',  label: 'Name', type: 'text' },
    ]},
  ],
}
```

While this configuration works, with the value of `id` actually saving in Mongo as `_id`

```typescript
export const Tags: CollectionConfig = {
  slug: 'tags',
  fields: [
    { name: 'id',  label: 'Name', type: 'text' },
  ],
}
```

### Payload Version

2.5.0

### Adapters and Plugins

db-mongodb

### PR DESCRIPTION
**Pull request by paulpopus**
Closes https://github.com/payloadcms/payload/issues/4546
Closes https://github.com/payloadcms/payload/issues/4628

## Description

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: packages/payload/src/collections/graphql/init.ts [hunk 1]
```diff
@@ -76,7 +77,10 @@ function initCollectionsGraphQL(payload: Payload): void {
 
     collection.graphQL = {} as Collection['graphQL']
 
-    const idField = fields.find((field) => fieldAffectsData(field) && field.name === 'id')
+    const idField =
```
Comment (jmikrut) [inline packages/payload/src/collections/graphql/init.ts:80]: This variable is not named appropriately. You are setting this const to a boolean, but on reading the code, I was thinking that it was the ID field itself. I know this is a problem with the code before you came in, but just some quick feedback for the future - feel free to rename any weird variables like this to `hasIDField` or similar if you find them.

File: packages/payload/src/collections/operations/create.ts [hunk 2]
```diff
@@ -110,8 +111,8 @@ async function create<TSlug extends keyof GeneratedTypes['collections']>(
     // /////////////////////////////////////
 
     const hasIdField =
-      collectionConfig.fields.findIndex((field) => fieldAffectsData(field) && field.name === 'id') >
-      -1
+      flattenFields(collectionConfig.fields).findIndex((field) => field.name === 'id') > -1
```
Comment (jmikrut) [inline packages/payload/src/collections/operations/create.ts:114]: It's relatively unfortunate that we have to `flattenFields` on every create, because it's a loop and is not necessary most of the time. Would be nice to, in the future, somehow store if there is a custom ID on a collection by collection basis on Payload itself, as the collections are being instantiated. Not necessary to change now, but something to keep on the radar.

File: packages/payload/src/graphql/schema/buildWhereInputType.ts [hunk 3]
```diff
@@ -44,10 +45,12 @@ const buildWhereInputType = ({
...
   // field types with nested paths.
 
-  let idField: FieldAffectingData | undefined
+  let idField = flattenFields(fields).find(
+    (field) => fieldAffectsData(field) && field.name === 'id',
+  )
 
   const fieldTypes = fields.reduce((schema, field) => {
-    if (fieldAffectsData(field) && field.name === 'id') idField = field
+    /* if (fieldAffectsData(field) && field.name === 'id') idField = field */
```
Comment (jmikrut) [inline packages/payload/src/graphql/schema/buildWhereInputType.ts:53]: Should this be removed?

File: packages/payload/src/collections/operations/create.ts (hunk 2 above)
Comment (paulpopus) [reply packages/payload/src/collections/operations/create.ts:114]: Added a @todo note in there, sounds like a good idea

Comment (DanRibbens) [reply packages/payload/src/collections/operations/create.ts:114]: We should just write a `findField` utility function that works like flatten fields but returns as soon as it has a match. That will be more performent than flattening all fields, and looping again to find it.
