### PR TITLE
fix(richtext-lexical): make the toolbar indent button consider the disabledNodes property on IndentFeature

### LINKED ISSUE #11677: The toolbar's indent button does not consider the disabledNodes property in IndentFeature
### Describe the Bug

The toolbar's indent button does not consider the disabledNodes property in IndentFeature

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload

### Reproduction Steps

1. add this to a rich text field:
```ts
editor: lexicalEditor({
  features: ({ defaultFeatures }) => [
    ...defaultFeatures,
    IndentFeature({
      // the array must contain the "type" property of registered indentable nodes
      disabledNodes: ['paragraph', 'listitem'],
    }),
  ],
}),
```
2. If you put the cursor over a paragraph or listitem you will still see the option to indent it in the toolbar, although it will do nothing.

### Which area(s) are affected? (Select all that apply)

plugin: richtext-lexical

### Environment Info

```text
Payload: 3.28.1
```

### PR DESCRIPTION
**Pull request by GermanJablo**
Fixes #11677

### CODE REVIEW

File: packages/richtext-lexical/src/features/indent/client/index.tsx [hunk 1]
```diff
@@ -80,17 +87,31 @@ const toolbarGroups: ToolbarGroup[] = [
...
 ]
 
-export const IndentFeatureClient = createClientFeature({
-  plugins: [
-    {
-      Component: IndentPlugin,
-      position: 'normal',
+export const IndentFeatureClient = createClientFeature<IndentFeatureProps>(({ props }) => {
+  const disabledNodes = props.disabledNodes ?? []
+  return {
```
Comment (AlessioGr) [inline packages/richtext-lexical/src/features/indent/client/index.tsx:92]: Need to return 

`sanitizedClientFeatureProps: props,`

File: packages/richtext-lexical/src/features/indent/client/index.tsx [hunk 2]
```diff
@@ -80,17 +87,31 @@ const toolbarGroups: ToolbarGroup[] = [
...
+    plugins: [
+      {
+        Component: () => IndentPlugin({ clientProps: props }),
```
Comment (AlessioGr) [inline packages/richtext-lexical/src/features/indent/client/index.tsx:95]: After returning `sanitizedClientFeatureProps`, this should be unnecessary - IndentPlugin will automatically receive the client props

**Review by AlessioGr — CHANGES_REQUESTED** [review]

**Review by AlessioGr — APPROVED** [review]
