### PR TITLE
fix(ui): preview button not responding to conditional URL

### LINKED ISSUE #14241: Preview button throws error when preview URL is null
### Describe the Bug

First, thanks @jacobsfletch for the ongoing work on improving Live Preview! This issue is related to https://github.com/payloadcms/payload/pull/14012, but concerns the Preview button (not the Live Preview button):

When the function that generates the preview URL returns null (e.g., because the page slug is not defined yet), the Preview button is still rendered. Clicking it shows the error message: “There was a problem previewing this document.”

**Current behavior**:  
If function that generates the preview URL returns null, the Preview button still appears. On click, Payload shows: “There was a problem previewing this document.”

**Expected behavior**: 
The Preview button should be conditionally hidden when no URL is available — consistent with the Live Preview button behavior.

https://github.com/user-attachments/assets/6760b0da-7ad5-49a8-9ad8-21ff8b746bd0

### Link to the code that reproduces this issue

https://github.com/jhb-dev/payload-conditional-preview-issue

### Reproduction Steps

1. Run the Payload instance of the reproduction repository.
3. Open the Pages collection and click Create new.
5. Ensure no slug is set.
7. Click the Preview button.
9. Observe the error: “There was a problem previewing this document.”

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

```text
Binaries:
  Node: 24.3.0
  npm: 11.4.2
  Yarn: N/A
  pnpm: 10.12.4
Relevant Packages:
  payload: 3.60.0
  next: 15.4.4
  @payloadcms/db-mongodb: 3.60.0
  @payloadcms/next/utilities: 3.60.0
  @payloadcms/payload-cloud: 3.60.0
  @payloadcms/richtext-lexical: 3.60.0
  @payloadcms/ui/shared: 3.60.0
  react: 19.1.0
  react-dom: 19.1.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:40 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6041
  Available memory (MB): 24576
  Available CPU cores: 14
```

### PR DESCRIPTION
**Pull request by paulpopus**
Fixes #14241 and #11253.

Preview URL is now part of the form state as well so we can conditionally show the preview button based on its value, previously this was not possible because we were fetching the URL on click. Similar to #14012.

### CODE REVIEW

File: packages/ui/src/elements/PreviewButton/index.tsx [hunk 1]
```diff
@@ -4,25 +4,29 @@ import type { PreviewButtonClientProps } from 'payload'
...
-  const { generatePreviewURL, label } = usePreviewURL()
+  const { previewURL } = usePreviewURL()
+  const { t } = useTranslation()
+
+  if (!previewURL) {
+    return null
+  }
 
   return (
     <button
```
Comment (jacobsfletch) [inline packages/ui/src/elements/PreviewButton/index.tsx]: This can now be an anchor tag for better a11y. The user will also be able to copy/paste the href once again ftw.

Comment (JarrodMFlesch) [reply packages/ui/src/elements/PreviewButton/index.tsx]: anchors cannot have on click events.

Comment (paulpopus) [reply packages/ui/src/elements/PreviewButton/index.tsx]: We wouldn't need onClick events is the point here, just my negligence to not change it

**Review by jacobsfletch — APPROVED** [review]
