### PR TITLE
fix: check hostname of upload url

### LINKED ISSUE #12876: storage-s3: Changing uploaded Media fails with "Blocked unsafe attempt" in v3.43.0
### Describe the Bug

s3 storage: Changing an image that has already been uploaded throws the following error: "An error occurred while uploading the file.. Blocked unsafe attempt to http://xxx" in Payload v3.43.0.

Earlier versions are not affected; there is no error after downgrading to version 3.42.

Thanks in advance for checking this out.

### Link to the code that reproduces this issue

pnpx create-payload-app@latest -t website

### Reproduction Steps

These steps are based on the Website template:

1.) Enable the s3 storage plugin:

```js
s3Storage({
      collections: {
        media: true,
      },
      bucket: process.env.S3_BUCKET_NAME || '',
      config: {
        region: process.env.S3_REGION || '',
        endpoint: process.env.S3_ENDPOINT || '',
        credentials: {
          accessKeyId: process.env.S3_ACCESS_KEY || '',
          secretAccessKey: process.env.S3_SECRET_KEY || '',
        },
      },
    }),
```

2) Upload an image to the Media collection – this works without any issues.

3) Edit the image, for example by changing the alt text, and click Save.

4) An error is thrown and the image is not updated. See the error in the logs:

```js
err: {
      "type": "FileRetrievalError",
      "message": "An error occurred while uploading the file.. Blocked unsafe attempt to http://localhost:3020/api/media/file/dummy-upload.png",
...}
```

### Which area(s) are affected? (Select all that apply)

plugin: cloud-storage

### Environment Info

```text
Binaries:
  Node: 20.19.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 10.3.0
Relevant Packages:
  payload: 3.43.0
  next: 15.3.0
  @payloadcms/db-mongodb: 3.43.0
  @payloadcms/email-nodemailer: 3.43.0
  @payloadcms/graphql: 3.43.0
  @payloadcms/live-preview: 3.43.0
  @payloadcms/live-preview-react: 3.43.0
  @payloadcms/next/utilities: 3.43.0
  @payloadcms/payload-cloud: 3.43.0
  @payloadcms/plugin-cloud-storage: 3.43.0
  @payloadcms/plugin-form-builder: 3.43.0
  @payloadcms/plugin-nested-docs: 3.43.0
  @payloadcms/plugin-redirects: 3.43.0
  @payloadcms/plugin-seo: 3.43.0
  @payloadcms/richtext-lexical: 3.43.0
  @payloadcms/storage-s3: 3.43.0
  @payloadcms/translations: 3.43.0
  @payloadcms/ui/shared: 3.43.0
  react: 19.1.0
  react-dom: 19.1.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.5.0: Tue Apr 22 19:53:27 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6041
  Available memory (MB): 24576
  Available CPU cores: 12
```

### PR DESCRIPTION
**Pull request by kendelljoseph**
Adds:
```ts
import { lookup } from 'dns/promises'
// ...
const { address } = await lookup(hostname)
// ...
return isSafeIp(address)
```

To ensure that an `ip` address is being verified. Previously, hostnames were being verified by `isSafeIp`.

Fixes: https://github.com/payloadcms/payload/issues/12876

### CODE REVIEW

File: packages/payload/src/uploads/safeFetch.ts [hunk 1]
```diff
@@ -57,13 +82,13 @@ export const safeFetch = async (...args: Parameters<typeof undiciFetch>) => {
         throw new Error(error.cause.message)
       } else {
         let stringifiedUrl: string | undefined | URL = undefined
-        if (typeof url === 'string' || url instanceof URL) {
-          stringifiedUrl = url
-        } else if (url instanceof Request) {
-          stringifiedUrl = url.url
+        if (typeof unverifiedUrl === 'string' || unverifiedUrl instanceof URL) {
```
Comment (denolfe) [inline packages/payload/src/uploads/safeFetch.ts]: nitpick: to prevent needing to use `String()` at all later, I would've expected something more like this:

```ts
let stringifiedUrl: string | undefined = undefined
if (typeof unverifiedUrl === 'string') {
  stringifiedUrl = unverifiedUrl
} else if (unverifiedUrl instanceof URL) {
  stringifiedUrl = unverifiedUrl.toString()
} else if (unverifiedUrl instanceof Request) {
  stringifiedUrl = unverifiedUrl.url
}

throw new Error(`Failed to fetch from ${stringifiedUrl}, ${error.message}`)
```

Not necessary, but worth noting.

**Review by denolfe — APPROVED** [review]

File: packages/payload/src/uploads/safeFetch.ts [hunk 2]
```diff
@@ -24,12 +25,27 @@ const isSafeIp = (ip: string) => {
   return true
 }
 
+/**
+ * Checks if a hostname or IP address is safe to fetch from.
+ * @param hostname a hostname or IP address
+ * @returns
+ */
+const isSafe = async (hostname: string) => {
+  // return isSafeIp(hostname)
```
Comment (denolfe) [inline packages/payload/src/uploads/safeFetch.ts]: Looks like a stray comment here that needs to be cleaned up.

**Review by denolfe — CHANGES_REQUESTED** [review]

File: packages/payload/src/uploads/safeFetch.ts (hunk 1 above)
Comment (kendelljoseph) [reply packages/payload/src/uploads/safeFetch.ts]: No problem, I'll update this.

**Review by denolfe — APPROVED** [review]
