### PR TITLE
fix: full image urls stored in DB

### LINKED ISSUE #14562: Upload collection url and thumbnailURL fields are inconsistently stored in the database
### Describe the Bug

When creating a new document in an upload-enabled collection (e.g. when uploading a file), the `url` and `thumbnailURL` fields are not stored in the database.
Only after saving the document again (for example, when updating the `alt` text), the `url` is persisted to the database.

This happens both without using any storage adapter and when using any of the storage adapters. It also affects the `url` field of image sizes.

By looking at Payload’s source code for uploads, I noticed that the default `url` field (as well as `thumbnailURL` and the `url` fields for image sizes) [automatically get an afterRead hook attached](https://github.com/payloadcms/payload/blob/bd6decf1d8349c11ba6ca0d8476c4223c6cb13ba/packages/payload/src/uploads/getBaseFields.ts#L138), which calls the `generateURL` function.
This explains why the `url` is stored in the database only after the first update — because during the read operation from the database, the `url` is generated based on the filename, then present in the document on save, and therefore persisted.

### Expected behaviour
The `url` fields should either never be stored in the database (virtual field) or always be stored consistently.

### Actual behaviour

The `url` fields are not stored in the database on upload, but they are persisted after the first update.

### Possible solution
It would make sense to add `virtual: true` to the `url` fields that are automatically created by Payload.
Otherwise, if someone enables `disablePayloadAccessControl` when there are already images in the database, all URLs in the database would incorrectly point to `/api/media` instead of the actual file source.

### More context

I noticed this issue because sometimes my custom `adminThumbnail` function received the originalDoc with a `url` field set and sometimes not, which is caused by this inconsistency.

### Reproduction video

https://github.com/user-attachments/assets/2185af1f-1e76-45ca-b709-370157c1c866

### Link to the code that reproduces this issue

https://github.com/jhb-dev/payload-inconsistent-storing-of-upload-url-field

### Reproduction Steps

1. run the Payload app of the linked reproduction repository (blank template without any storage adapters or the payload-cloud plugin)
2. create a new media document by uploading a file
3. inspect the URL field in the database (it's not present)
4. update the media document (e.g. update the alt text)
5. inspect the URL field in the database (it's present now).

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Binaries:
  Node: 24.3.0
  npm: 11.4.2
  Yarn: N/A
  pnpm: 10.12.4
Relevant Packages:
  payload: 3.63.0
  next: 15.4.7
  @payloadcms/db-mongodb: 3.63.0
  @payloadcms/graphql: 3.63.0
  @payloadcms/next/utilities: 3.63.0
  @payloadcms/richtext-lexical: 3.63.0
  @payloadcms/translations: 3.63.0
  @payloadcms/ui/shared: 3.63.0
  react: 19.1.0
  react-dom: 19.1.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:40 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6041
  Available memory (MB): 24576
  Available CPU cores: 14
```

### LINKED ISSUE #14945: Cannot edit image when `serverURL` is set
### Describe the Bug

Following the reproduction steps below, this is the error I get:

```
[23:59:21] ERROR: There was a problem while uploading the file. Blocked unsafe attempt to localhost
    err: {
      "type": "FileRetrievalError",
      "message": "There was a problem while uploading the file. Blocked unsafe attempt to localhost",
      "stack":
          FileRetrievalError: There was a problem while uploading the file. Blocked unsafe attempt to localhost
              at generateFileData (file:///home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/payload/dist/uploads/generateFileData.js:72:19)
              at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
              at async updateByIDOperation (file:///home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/payload/dist/collections/operations/updateByID.js:94:61)
              at async updateByIDHandler (file:///home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/payload/dist/collections/endpoints/updateByID.js:9:17)
              at async handleEndpoints (file:///home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/payload/dist/utilities/handleEndpoints.js:191:26)
              at async eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/next/dist/routes/rest/index.js:30:20)
              at async AppRouteRouteModule.do (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:5:38782)
              at async AppRouteRouteModule.handle (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:5:45984)
              at async responseGenerator (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&page=%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&appPaths=&pagePath=private-next-app-dir%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute.ts&appDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D&isGlobalNotFoundEnabled=!:206:38)
              at async AppRouteRouteModule.handleResponse (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:1:183692)
              at async handleResponse (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&page=%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&appPaths=&pagePath=private-next-app-dir%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute.ts&appDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D&isGlobalNotFoundEnabled=!:268:32)
              at async handler (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&page=%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&appPaths=&pagePath=private-next-app-dir%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute.ts&appDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D&isGlobalNotFoundEnabled=!:320:13)
              at async doRender (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:1592:34)
              at async DevServer.renderToResponseWithComponentsImpl (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:1934:13)
              at async DevServer.renderPageComponent (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:2400:24)
              at async DevServer.renderToResponseImpl (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:2440:32)
              at async DevServer.pipeImpl (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:1035:25)
              at async NextNodeServer.handleCatchallRenderRequest (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/next-server.js:393:17)
              at async DevServer.handleRequestImpl (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:925:17)
              at async /home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/dev/next-dev-server.js:398:20
              at async Span.traceAsyncFn (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/trace/trace.js:157:20)
              at async DevServer.handleRequest (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/dev/next-dev-server.js:394:24)
              at async invokeRender (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/lib/router-server.js:239:21)
              at async handleRequest (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/lib/router-server.js:436:24)
              at async requestHandlerImpl (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/lib/router-server.js:464:13)
              at async Server.requestListener (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/lib/start-server.js:218:13)
      "data": null,
      "isOperational": true,
      "isPublic": false,
      "status": 500,
      "name": "FileRetrievalError"
    }
 PATCH /api/media/1?depth=0&fallback-locale=null&uploadEdits%5Bcrop%5D%5Bunit%5D=%25&uploadEdits%5Bcrop%5D%5Bx%5D=0&uploadEdits%5Bcrop%5D%5By%5D=0&uploadEdits%5Bcrop%5D%5Bwidth%5D=74.56&uploadEdits%5Bcrop%5D%5Bheight%5D=77&uploadEdits%5BfocalPoint%5D%5Bx%5D=50&uploadEdits%5BfocalPoint%5D%5By%5D=50&uploadEdits%5BheightInPixels%5D=231&uploadEdits%5BwidthInPixels%5D=466 500 in 856ms
```

If I set `serverURL` to "http://127.0.0.1:3000", I get a slightly different error message:

```
[00:14:44] ERROR: There was a problem while uploading the file. Failed to fetch from http://127.0.0.1:3000/api/media/file/featured-image-cycling-in-hong-kong.jpg, Blocked unsafe attempt to 127.0.0.1
    err: {
      "type": "FileRetrievalError",
      "message": "There was a problem while uploading the file. Failed to fetch from http://127.0.0.1:3000/api/media/file/featured-image-cycling-in-hong-kong.jpg, Blocked unsafe attempt to 127.0.0.1",
      "stack":
          FileRetrievalError: There was a problem while uploading the file. Failed to fetch from http://127.0.0.1:3000/api/media/file/featured-image-cycling-in-hong-kong.jpg, Blocked unsafe attempt to 127.0.0.1
              at generateFileData (file:///home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/payload/dist/uploads/generateFileData.js:72:19)
              at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
              at async updateByIDOperation (file:///home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/payload/dist/collections/operations/updateByID.js:94:61)
              at async updateByIDHandler (file:///home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/payload/dist/collections/endpoints/updateByID.js:9:17)
              at async handleEndpoints (file:///home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/payload/dist/utilities/handleEndpoints.js:191:26)
              at async eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/next/dist/routes/rest/index.js:30:20)
              at async AppRouteRouteModule.do (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:5:38782)
              at async AppRouteRouteModule.handle (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:5:45984)
              at async responseGenerator (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&page=%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&appPaths=&pagePath=private-next-app-dir%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute.ts&appDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D&isGlobalNotFoundEnabled=!:206:38)
              at async AppRouteRouteModule.handleResponse (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:1:183692)
              at async handleResponse (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&page=%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&appPaths=&pagePath=private-next-app-dir%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute.ts&appDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D&isGlobalNotFoundEnabled=!:268:32)
              at async handler (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&page=%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute&appPaths=&pagePath=private-next-app-dir%2F(payload)%2Fapi%2F%5B...slug%5D%2Froute.ts&appDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Fjeff%2FCode%2Fpersonal%2Fpayload%2Fissues%2Fserver-url-edit-image-blocked-unsafe-attempt&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D&isGlobalNotFoundEnabled=!:320:13)
              at async doRender (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:1592:34)
              at async DevServer.renderToResponseWithComponentsImpl (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:1934:13)
              at async DevServer.renderPageComponent (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:2400:24)
              at async DevServer.renderToResponseImpl (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:2440:32)
              at async DevServer.pipeImpl (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:1035:25)
              at async NextNodeServer.handleCatchallRenderRequest (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/next-server.js:393:17)
              at async DevServer.handleRequestImpl (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/base-server.js:925:17)
              at async /home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/dev/next-dev-server.js:398:20
              at async Span.traceAsyncFn (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/trace/trace.js:157:20)
              at async DevServer.handleRequest (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/dev/next-dev-server.js:394:24)
              at async invokeRender (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/lib/router-server.js:239:21)
              at async handleRequest (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/lib/router-server.js:436:24)
              at async requestHandlerImpl (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/lib/router-server.js:464:13)
              at async Server.requestListener (/home/jeff/Code/personal/payload/issues/server-url-edit-image-blocked-unsafe-attempt/node_modules/next/dist/server/lib/start-server.js:218:13)
      "data": null,
      "isOperational": true,
      "isPublic": false,
      "status": 500,
      "name": "FileRetrievalError"
    }
 PATCH /api/media/1?depth=0&fallback-locale=null&uploadEdits%5Bcrop%5D%5Bunit%5D=%25&uploadEdits%5Bcrop%5D%5Bx%5D=29.280397022332505&uploadEdits%5Bcrop%5D%5By%5D=0&uploadEdits%5Bcrop%5D%5Bwidth%5D=70.71960297766749&uploadEdits%5Bcrop%5D%5Bheight%5D=100&uploadEdits%5BfocalPoint%5D%5Bx%5D=50&uploadEdits%5BfocalPoint%5D%5By%5D=50&uploadEdits%5BheightInPixels%5D=105&uploadEdits%5BwidthInPixels%5D=285 500 in 164ms
```

Payload appears to be treating local image edits as if they are remote file accesses.

This appears to be a continuation of #12876 (ping @kendelljoseph) - it appears some of that issue's commenters were experiencing this issue.

A workaround is to add Payload's server details to `skipSafeFetch` for the upload collection, e.g.:

```
  upload: {
    skipSafeFetch: [
      {
        hostname: 'localhost',
        port: '3000',
        protocol: 'http',
      },
    ],
  },
```

### Link to the code that reproduces this issue

https://github.com/jefferyto/payload-serverURL-edit-image-blocked-unsafe-attempt

### Reproduction Steps

1. Checkout reproduction repo (note that `serverURL` in src/payload.config.ts is set to "http://localhost:3000"), `npm install`, `npm run dev`
2. Open http://localhost:3000/admin, create first user, upload an image
3. Edit the image (click "Edit Image", change cropping, click "Apply Changes") and attempt to save the edited image

### Which area(s) are affected?

area: core

### Environment Info

```text
Binaries:
  Node: 24.11.1
  npm: 11.6.4
  Yarn: 1.22.22
  pnpm: 10.26.0
Relevant Packages:
  payload: 3.68.5
  next: 15.4.10
  @payloadcms/db-sqlite: 3.68.5
  @payloadcms/drizzle: 3.68.5
  @payloadcms/graphql: 3.68.5
  @payloadcms/next/utilities: 3.68.5
  @payloadcms/richtext-lexical: 3.68.5
  @payloadcms/translations: 3.68.5
  @payloadcms/ui/shared: 3.68.5
  react: 19.2.1
  react-dom: 19.2.1
Operating System:
  Platform: linux
  Arch: x64
  Version: #8-Ubuntu SMP PREEMPT_DYNAMIC Fri Nov 14 21:44:46 UTC 2025
  Available memory (MB): 7224
  Available CPU cores: 4
```

### PR DESCRIPTION
**Pull request by JarrodMFlesch**
### Issue

URL field values can be set as full URLs, but should be stored as paths if they are on the local file system. Previously this was not being handled which is not portable, you should be able to change your serverURL without needing to update the DB documents.

This PR adds a beforeChange hook to the url fields that converts the data to the correct relative url for local files. If the url is external, then that gets returned as is.

### Why 
- fixes https://github.com/payloadcms/payload/issues/14562 where urls would not be set on create but only after the fixes document was updated (fixed with beforeChange hook)
- fixes https://github.com/payloadcms/payload/issues/14945 where URLs are being fetched via fetch instead of with local filesystem reads (fixed with beforeChange hook)

#### Flow before:
- create --> no URL present --> afterRead returns URL --> update happens with that returned URL and it is saved

#### New Flow:
- create --> beforeChange hook creates the URL --> saved in DB

The new flow also ensures URLs are saved as relative URLs when stored on the local filesystem. This makes files more portable, removing the need to update the DB i.e. if you change your domain for example. 

**URL fields are stored in the DB as:**
- relative when on the local filesystem i.e. `/:apiRoute/:collectionSlug/file/:filename`
- absolute when external i.e. `https://some-fake-external-website.com/images/1`

**URL field values are returned as:**
- absolute if serverURL is set on the config i.e. `https://your-domain.com/:apiRoute/:collectionSlug/file/:filename`
- relative if serverURL is not set and the value is a relative path i.e. `/:apiRoute/:collectionSlug/file/:filename`
- absolute if the url is external i.e. `https://some-fake-external-website.com/images/1`

The majority of the files added in this PR were moved from the imageResizer file.
- [createImageSize.ts](https://github.com/payloadcms/payload/pull/15089/changes#diff-c9bea14458c4f95b4a07c143e13ad40e9d76f69a78ed1e0aaa42660d874ef7ff)
- [createImageSizes.ts](https://github.com/payloadcms/payload/pull/15089/changes#diff-c3ef20c6b9afc09034860d4a2c65ee0f0c05a448c0b8e41c064d30a07f39cf48)
- [extractHeightFromImage.ts](https://github.com/payloadcms/payload/pull/15089/changes#diff-42b5eac52d268d5b6ac72299557ce8fe12acbd564ff7e516d727bfc36010e677)
- [generateImageSizeFilename.ts](https://github.com/payloadcms/payload/pull/15089/changes#diff-672120daaa59eec3cf36428851e5440929db80ac99e352fc17640b73db87879a)
- [getImageResizeAction.ts](https://github.com/payloadcms/payload/pull/15089/changes#diff-16dfbbd365a6e05ea42ba10716d038f369d27fd090fe718759c082e5c79eef37)
- [parseFilename.ts](https://github.com/payloadcms/payload/pull/15089/changes#diff-c3b8939f4acd59871ceebe38e591c3028b36834d3baf08ce94a01d454d610f64)
- [sanitizeResizeConfig.ts](https://github.com/payloadcms/payload/pull/15089/changes#diff-9f567e4597f13ff207789dcaa41399a2e0878c652a30a7973a44b09e2d6f5dde)

## Clean up old DB entries

If you would like to clean up pre-existing (uploads added before 3.71.0) you can use the following script:

```ts
/**
 * Migration script to convert full image URLs to relative paths in the database.
 *
 * Before Payload v3.71 (PR #15089), upload collections stored full URLs including the serverURL.
 * After the fix, URLs are stored as relative paths for local files.
 *
 * This script uses direct database operations (payload.db) to:
 * - Read raw values without afterRead hooks transforming them
 * - Update values without beforeChange hooks re-adding the serverURL
 *
 * Usage:
 *   1. Update the configuration below (SERVER_URL_TO_STRIP)
 *   2. Run: npx tsx scripts/migrate-image-urls.ts
 *
 * Options:
 *   --dry-run    Preview changes without modifying the database
 */

import 'dotenv/config'

import type { CollectionSlug, Payload } from 'payload'

import * as readline from 'readline'

import { getPayload } from 'payload'

import config from '@payload-config'

// =============================================================================
// CONFIGURATION - Update these values for your project
// =============================================================================

/**
 * The server URL prefix to strip from stored URLs.
 * Example: 'https://your-old-domain.com' or 'http://localhost:3000'
 */
const SERVER_URL_TO_STRIP = 'PLACEHOLDER_SERVER_URL'

/**
 * Batch size for processing documents.
 */
const BATCH_SIZE = 100

/**
 * Get all upload collection slugs from the Payload config.
 */
function getUploadCollections(payload: Payload): string[] {
  return Object.values(payload.collections)
    .filter((collection) => collection.config.upload)
    .map((collection) => collection.config.slug)
}

/**
 * Check if a collection has versions enabled.
 */
function hasVersions(payload: Payload, collectionSlug: string): boolean {
  const collection = payload.collections[collectionSlug as CollectionSlug]
  return Boolean(collection?.config.versions)
}

// =============================================================================
// MIGRATION LOGIC
// =============================================================================

type ImageSizes = Record<string, { url?: string | null } | undefined>

interface UploadDoc {
  id: string | number
  url?: string | null
  thumbnailURL?: string | null
  sizes?: ImageSizes
  [key: string]: unknown
}

function stripServerUrl(url: string | null | undefined): string | null | undefined {
  if (!url || typeof url !== 'string') {
    return url
  }

  if (url.startsWith(SERVER_URL_TO_STRIP)) {
    return url.slice(SERVER_URL_TO_STRIP.length)
  }

  return url
}

function processDocument(doc: UploadDoc): { updated: UploadDoc; hasChanges: boolean } {
  let hasChanges = false
  const updated: UploadDoc = { ...doc }

  // Process main url
  const newUrl = stripServerUrl(doc.url)
  if (newUrl !== doc.url) {
    updated.url = newUrl
    hasChanges = true
  }

  // Process thumbnailURL
  const newThumbnailUrl = stripServerUrl(doc.thumbnailURL)
  if (newThumbnailUrl !== doc.thumbnailURL) {
    updated.thumbnailURL = newThumbnailUrl
    hasChanges = true
  }

  // Process sizes
  if (doc.sizes && typeof doc.sizes === 'object') {
    const newSizes: ImageSizes = {}
    let sizesChanged = false

    for (const [sizeName, sizeData] of Object.entries(doc.sizes)) {
      if (sizeData && typeof sizeData === 'object' && 'url' in sizeData) {
        const newSizeUrl = stripServerUrl(sizeData.url)
        if (newSizeUrl !== sizeData.url) {
          newSizes[sizeName] = { ...sizeData, url: newSizeUrl }
          sizesChanged = true
        } else {
          newSizes[sizeName] = sizeData
        }
      } else {
        newSizes[sizeName] = sizeData
      }
    }

    if (sizesChanged) {
      updated.sizes = newSizes
      hasChanges = true
    }
  }

  return { updated, hasChanges }
}

function logDocumentChanges(params: {
  doc: UploadDoc
  updatedDoc: UploadDoc
  prefix?: string
}): void {
  const { doc, updatedDoc, prefix = '' } = params
  if (updatedDoc.url !== doc.url) {
    console.log(`${prefix}  url: "${doc.url}" -> "${updatedDoc.url}"`)
  }
  if (updatedDoc.thumbnailURL !== doc.thumbnailURL) {
    console.log(`${prefix}  thumbnailURL: "${doc.thumbnailURL}" -> "${updatedDoc.thumbnailURL}"`)
  }
  if (updatedDoc.sizes && doc.sizes) {
    for (const [sizeName, sizeData] of Object.entries(updatedDoc.sizes)) {
      const originalSize = doc.sizes[sizeName]
      if (originalSize && sizeData && sizeData.url !== originalSize.url) {
        console.log(`${prefix}  sizes.${sizeName}.url: "${originalSize.url}" -> "${sizeData.url}"`)
      }
    }
  }
}

async function migrateCollection(params: {
  collectionSlug: string
  dryRun: boolean
  payload: Payload
}): Promise<{ processed: number; updated: number }> {
  const { collectionSlug, dryRun, payload } = params
  let processed = 0
  let updated = 0
  let page = 1
  let hasMore = true

  console.log(`\nMigrating collection: ${collectionSlug}`)
  console.log('-'.repeat(50))

  while (hasMore) {
    // Use payload.db.find to get raw values without afterRead hooks
    const result = await payload.db.find({
      collection: collectionSlug as CollectionSlug,
      limit: BATCH_SIZE,
      page,
      pagination: true,
    })

    for (const doc of result.docs as UploadDoc[]) {
      processed++
      const { updated: updatedDoc, hasChanges } = processDocument(doc)

      if (hasChanges) {
        updated++

        if (dryRun) {
          console.log(`[DRY RUN] Would update document ${doc.id}:`)
          logDocumentChanges({ doc, updatedDoc })
        } else {
          // Use payload.db.updateOne to bypass beforeChange hooks
          await payload.db.updateOne({
            collection: collectionSlug as CollectionSlug,
            id: doc.id,
            data: {
              url: updatedDoc.url,
              thumbnailURL: updatedDoc.thumbnailURL,
              sizes: updatedDoc.sizes,
            },
          })
          console.log(`Updated document ${doc.id}`)
        }
      }
    }

    hasMore = result.hasNextPage ?? false
    page++

    // Progress indicator
    if (processed % 500 === 0) {
      console.log(`  Processed ${processed} documents...`)
    }
  }

  return { processed, updated }
}

interface VersionDoc {
  _id: unknown
  version: UploadDoc
  [key: string]: unknown
}

interface MongoCollection {
  find: () => {
    skip: (n: number) => {
      limit: (n: number) => {
        toArray: () => Promise<VersionDoc[]>
      }
    }
  }
  countDocuments: () => Promise<number>
  updateOne: (
    filter: { _id: unknown },
    update: { $set: Record<string, unknown> },
  ) => Promise<unknown>
}

async function migrateVersions(params: {
  collectionSlug: string
  dryRun: boolean
  payload: Payload
}): Promise<{ processed: number; updated: number }> {
  const { collectionSlug, dryRun, payload } = params
  let processed = 0
  let updated = 0
  let skip = 0

  const versionsCollectionName = `_${collectionSlug}_versions`

  console.log(`\nMigrating versions: ${versionsCollectionName}`)
  console.log('-'.repeat(50))

  // Access MongoDB directly since _versions collections aren't exposed via payload.db
  const db = (payload.db as unknown as { connection: { db: { collection: (name: string) => unknown } } })
    .connection.db
  const versionsCollection = db.collection(versionsCollectionName) as MongoCollection

  const totalCount = await versionsCollection.countDocuments()
  let hasMore = totalCount > 0

  while (hasMore) {
    const docs = await versionsCollection.find().skip(skip).limit(BATCH_SIZE).toArray()

    if (docs.length === 0) {
      hasMore = false
      break
    }

    for (const versionDoc of docs) {
      processed++

      // The actual document data is nested in the 'version' field
      const doc = versionDoc.version
      if (!doc) continue

      const { updated: updatedDoc, hasChanges } = processDocument(doc)

      if (hasChanges) {
        updated++

        if (dryRun) {
          console.log(`[DRY RUN] Would update version ${versionDoc._id}:`)
          logDocumentChanges({ doc, updatedDoc })
        } else {
          // Update the version field directly in MongoDB
          await versionsCollection.updateOne(
            { _id: versionDoc._id },
            {
              $set: {
                'version.url': updatedDoc.url,
                'version.thumbnailURL': updatedDoc.thumbnailURL,
                'version.sizes': updatedDoc.sizes,
              },
            },
          )
          console.log(`Updated version ${versionDoc._id}`)
        }
      }
    }

    skip += docs.length
    hasMore = skip < totalCount

    // Progress indicator
    if (processed % 500 === 0) {
      console.log(`  Processed ${processed} versions...`)
    }
  }

  return { processed, updated }
}

async function main(): Promise<void> {
  if (SERVER_URL_TO_STRIP === 'PLACEHOLDER_SERVER_URL') {
    console.error('Please update the SERVER_URL_TO_STRIP constant in the script before running.')
    process.exit(1)
  }
  const dryRun = process.argv.includes('--dry-run')
  const payload = await getPayload({ config })
  const uploadCollections = getUploadCollections(payload)

  console.log('='.repeat(60))
  console.log('Image URL Migration Script')
  console.log('='.repeat(60))
  console.log(`Server URL to strip: ${SERVER_URL_TO_STRIP}`)
  console.log(`Upload collections found: ${uploadCollections.join(', ')}`)

  const collectionsWithVersions = uploadCollections.filter((slug) => hasVersions(payload, slug))
  if (collectionsWithVersions.length > 0) {
    console.log(`Collections with versions: ${collectionsWithVersions.join(', ')}`)
  }

  console.log(`Mode: ${dryRun ? 'DRY RUN (no changes will be made)' : 'LIVE'}`)
  console.log('='.repeat(60))

  if (!dryRun) {
    console.log('\n⚠️  WARNING: This will modify your database!')
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    })
    const answer = await new Promise<string>((resolve) => {
      rl.question('Type "yes" to continue: ', resolve)
    })
    rl.close()
    if (answer.toLowerCase() !== 'yes') {
      console.log('Migration cancelled.')
      process.exit(0)
    }
  }

  let totalProcessed = 0
  let totalUpdated = 0
  let totalVersionsProcessed = 0
  let totalVersionsUpdated = 0

  for (const collectionSlug of uploadCollections) {
    try {
      // Migrate main collection documents
      const { processed, updated } = await migrateCollection({
        collectionSlug,
        dryRun,
        payload,
      })
      totalProcessed += processed
      totalUpdated += updated

      // Migrate versions if enabled
      if (hasVersions(payload, collectionSlug)) {
        const { processed: versionsProcessed, updated: versionsUpdated } = await migrateVersions({
          collectionSlug,
          dryRun,
          payload,
        })
        totalVersionsProcessed += versionsProcessed
        totalVersionsUpdated += versionsUpdated
      }
    } catch (error) {
      console.error(`Error migrating collection ${collectionSlug}:`, error)
    }
  }

  console.log('\n' + '='.repeat(60))
  console.log('Migration Summary')
  console.log('='.repeat(60))
  console.log(`Total documents processed: ${totalProcessed}`)
  console.log(`Total documents ${dryRun ? 'that would be updated' : 'updated'}: ${totalUpdated}`)
  if (totalVersionsProcessed > 0) {
    console.log(`Total versions processed: ${totalVersionsProcessed}`)
    console.log(`Total versions ${dryRun ? 'that would be updated' : 'updated'}: ${totalVersionsUpdated}`)
  }

  if (dryRun) {
    console.log('\nTo apply changes, run without --dry-run flag')
  }

  process.exit(0)
}

main().catch((error) => {
  console.error('Migration failed:', error)
  process.exit(1)
})
```

### CODE REVIEW

**Comment by jhb-dev** [comment]
Hi @JarrodMFlesch, it seems like this PR is somewhat related to the following issue I created a while back: https://github.com/payloadcms/payload/issues/14562

**Comment by JarrodMFlesch** [comment]
@jhb-dev yes this should resolve that open issue since it uses a before change hook to set the correct url.

I brought up the issue regarding the /api/media/file/filename being stored earlier today as well. Personally I would like to see it just stored as undefined or null if the file is stored locally. But decided to keep it as is until 4.0 since it is technically a breaking change.

File: test/uploads/config.ts [hunk 1]
```diff
@@ -1239,7 +1239,7 @@ export default buildConfigWithDefaults({
       })
     }
   },
-  serverURL: undefined,
+  serverURL: 'http://localhost:3000',
```
Comment (DanRibbens) [inline test/uploads/config.ts]: As we discussed, may not want to be hardcoding this.

**Review by DanRibbens — CHANGES_REQUESTED** [review]
Looking good other than the test config change.

File: test/uploads/config.ts (hunk 1 above)
Comment (DanRibbens) [reply test/uploads/config.ts]: We should update the description to explain that we did move functions around, but that they were unchanged.

Comment (JarrodMFlesch) [reply test/uploads/config.ts]: I removed the serverURL and added context to the PR desc.

**Review by DanRibbens — APPROVED** [review]

**Comment by mbifulco** [comment]
Stoked to see this merged, thank you! I think this may also address my PR here - https://github.com/payloadcms/payload/pull/14250

**Comment by DanRibbens** [comment]
> Stoked to see this merged, thank you! I think this may also address my PR here - #14250

Does that mean we can close #14250?

**Comment by mbifulco** [comment]
@DanRibbens I think so - I'll test as soon as this makes it into a release

**Comment by jhb-dev** [comment]
Hi @JarrodMFlesch, in the PR description it states that for external files, the absolute URL is stored in the DB. 

However, I don't see this behavior when using the S3 plugin. In the API result, the URL field holds the actual S3 URL, but in the DB, the relative path to the file (`/api/images/...`) is stored.

I opened an issue with a reproduction: https://github.com/payloadcms/payload/issues/15382

**Comment by JarrodMFlesch** [comment]
> Hi @JarrodMFlesch, in the PR description it states that for external files, the absolute URL is stored in the DB. 
> 
> 
> 
> However, I don't see this behavior when using the S3 plugin. In the API result, the URL field holds the actual S3 URL, but in the DB, the relative path to the file (`/api/images/...`) is stored.
> 
> 
> 
> I opened an issue with a reproduction: https://github.com/payloadcms/payload/issues/15382

Ah the description should be updated, this was intended behavior. 

BUT I believe you are correct about when disablePayloadAccessControl is true that we should store the full url for external files.
