### PR TITLE
fix: incorrect duplication of data in admin ui

### LINKED ISSUE #3878: duplication of content causes incorrect checkbox value
### Link to reproduction

_No response_

### Describe the Bug

when using the "duplicate" function from the menu for an item in a collection, it sometimes causes a checkbox to have an incorrect value.

### To Reproduce

checkbox:

```
 {
      name: 'showContactCta',
      label: 'Show contact CTA',
      type: 'checkbox',
      localized: true
    }
```

Steps:
1. Create localized checkbox
2. Save EN as checked
3. Save ES as unchecked
4. Switch to EN
5. Duplicate Doc
6. Switch to ES
7. Checkbox will be checked, but should be unchecked

### Payload Version

8.0.13

### Adapters and Plugins

_No response_

### PR DESCRIPTION
**Pull request by JarrodMFlesch**
## Description

Fixes https://github.com/payloadcms/payload/issues/3878

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

Updates the duplicate requests, setting fallback locale to none: `?fallback-locale=none`. This way data is fetched and stored without using fallback data.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/payload/src/admin/components/elements/DuplicateDocument/index.tsx [hunk 1]
```diff
@@ -75,7 +76,7 @@ const Duplicate: React.FC<Props> = ({ id, collection, slug }) => {
         }
 
         const result = await requests[duplicateID ? 'patch' : 'post'](
-          `${serverURL}${api}/${slug}/${duplicateID}?locale=${locale}`,
+          `${serverURL}${api}/${slug}/${duplicateID}?locale=${locale}&fallback-locale=none`,
```
Comment (DanRibbens) [inline packages/payload/src/admin/components/elements/DuplicateDocument/index.tsx:79]: Great catch!

**Review by DanRibbens — APPROVED** [review]
