### PR TITLE
fix: Field in drawer cannot be edited

### LINKED ISSUE #2945: Field in drawer cannot be edited
### Link to reproduction

Not for now

### To Reproduce

This is just a reminder for a closed issue.: https://github.com/payloadcms/payload/issues/2815. More than one of us are reporting this but we got no replies. I guess the reason is the ticket is closed.

### Describe the Bug

https://github.com/payloadcms/payload/issues/2815

### Payload Version

1.10.2

### PR DESCRIPTION
**Pull request by AlessioGr**
Fixes #2945

### CODE REVIEW

File: src/admin/components/elements/ReactSelect/MultiValue/index.tsx [hunk 1]
```diff
@@ -53,7 +53,6 @@ export const MultiValue: React.FC<MultiValueProps<Option>> = (props) => {
         onMouseDown: (e) => {
           if (!disableMouseDown) {
             // we need to prevent the dropdown from opening when clicking on the drag handle, but not when a modal is open (i.e. the 'Relationship' field component)
-            e.preventDefault();
```
Comment (jacobsfletch) [inline src/admin/components/elements/ReactSelect/MultiValue/index.tsx:56]: @AlessioGr we need to be sure that the comment above is affected by removing this line. It was put here intentionally.

Comment (AlessioGr) [reply src/admin/components/elements/ReactSelect/MultiValue/index.tsx:56]: @jacobsfletch The stopPropagation() below seems to be enough. The drawer is not opening when you click on the handle.
