### PR TITLE
fix: upload fit not accounted for when editing focal point or crop

### LINKED ISSUE #4137: Editing images does not respect fit value
### Link to reproduction

private repo

### Describe the Bug

After the main image is edited, all sub-image sizes are created using the exact width/height value without the set fit value. For instance we set fit to 'inside' but the images are cropped.

### To Reproduce

Set fit value of image size to fit: 'inside'. Edit image. Resulting images are cropped.

Bildschirmfoto 2023-11-14 um 11 53 36

### Payload Version

2.1.1

### Adapters and Plugins

db-mongodb, bundler-webpack, live-preview

### PR DESCRIPTION
**Pull request by JessRynkar**
## Description

Editing the crop or focal point of an image will currently cancel out the `fit` position, these adjustments should only be applied when `fit` is not `contain` or `inside`.

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] Existing test suite passes locally with my changes

### CODE REVIEW

File: packages/payload/src/uploads/imageResizer.ts [hunk 1]
```diff
@@ -243,14 +244,14 @@ export default async function resizeAndTransformImageSizes({
...
         const prioritizeHeight = resizeAspectRatio < originalAspectRatio
-
         // Scale the image up or down to fit the resize dimensions
         const scaledImage = imageToResize.resize({
           height: prioritizeHeight ? resizeHeight : null,
           width: prioritizeHeight ? null : resizeWidth,
         })
         const { info: scaledImageInfo } = await scaledImage.toBuffer({ resolveWithObject: true })
 
+        console.log(scaledImageInfo)
```
Comment (denolfe) [inline packages/payload/src/uploads/imageResizer.ts:254]: I assume unintended 😁

**Review by denolfe — CHANGES_REQUESTED** [review]
Just one console.log to be removed, then it looks good to me.
