### PR TITLE
fix(db-mongodb): querying plan for collections ignoring indexes

### LINKED ISSUE #4651: Large `upload` collections unusable due to indexing issues
### Link to reproduction

_No response_

### Describe the Bug

We have an `images` collection with 520,000 records and there appears to be some sort of mismatch between the automatic indexes created and the way queries are being executed against this collection. It does look like Payload is automatically creating indexes for each `imageSize` we've specified:
image

But it does not look like these indexes are being used at all, every query on this collection examines all 520k records (and hence our ratio is 520,000:1)

Here's one of the offending queries:
```
{
  "type": "command",
  "ns": "project.images",
  "command": {
    "aggregate": "images",
    "pipeline": [
      {
        "$match": {
          "$and": [
            {
              "$or": [
                {
                  "filename": {
                    "$eq": "GettyImages-491433011.jpg"
                  }
                },
                {
                  "sizes.metaLarger.filename": {
                    "$eq": "GettyImages-491433011.jpg"
                  }
                },
                {
                  "sizes.metaSmaller.filename": {
                    "$eq": "GettyImages-491433011.jpg"
                  }
                },
                {
                  "sizes.hero.filename": {
                    "$eq": "GettyImages-491433011.jpg"
                  }
                },
                {
                  "sizes.large.filename": {
                    "$eq": "GettyImages-491433011.jpg"
                  }
                }
              ]
            }
          ]
        }
      },
      {
        "$group": {
          "_id": 1,
          "n": {
            "$sum": 1
          }
        }
      }
    ],
    "hint": {
      "_id": 1
    },
    "cursor": {},
    "$clusterTime": {
      "clusterTime": {
        "$timestamp": {
          "t": 1704210226,
          "i": 11
        }
      }
    },
    "$db": "project"
  },
  "planSummary": "IXSCAN { _id: 1 }",
  "keysExamined": 520981,
  "docsExamined": 520981,
  "cursorExhausted": true,
  "numYields": 567,
  "nreturned": 1,
  "queryHash": "C7173361",
  "queryFramework": "classic",
  "reslen": 253,
  "locks": {
    "FeatureCompatibilityVersion": {
      "acquireCount": {
        "r": 569
      }
    },
    "Global": {
      "acquireCount": {
        "r": 569
      }
    },
    "Mutex": {
      "acquireCount": {
        "r": 2
      }
    }
  },
  "readConcern": {
    "level": "local",
    "provenance": "implicitDefault"
  },
  "writeConcern": {
    "w": "majority",
    "wtimeout": 0,
    "provenance": "implicitDefault"
  },
  "storage": {},
  "protocol": "op_msg",
  "durationMillis": 10871,
  "v": "6.0.12"
}
```

### To Reproduce

n/a

### Payload Version

2.1.0

### Adapters and Plugins

db-mongodb, plugin-cloud-storage

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

fixes #4651 

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by ssyberg** [comment]
💪🏼

File: packages/db-mongodb/src/find.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export const find: Find = async function find(
     useEstimatedCount,
   }
 
-  if (!useEstimatedCount && this.disableIndexHints !== true) {
+  if (!useEstimatedCount && Object.keys(query).length === 0 && this.disableIndexHints !== true) {
     // Improve the performance of the countDocuments query which is used if useEstimatedCount is set to false by adding a hint.
```
Comment (AlessioGr) [inline packages/db-mongodb/src/find.ts:59]: I'd change the comment to something like

// Improve the performance of the countDocuments query which is used if useEstimatedCount is set to false by adding a hint. By default, if no hint is provided, MongoDB does not use an indexed field to count the returned documents, which makes queries very slow. This only happens when no query (filter) is provided. If one is provided, it uses the correct indexed field

as, without knowing the context, it's unclear why this code is needed

**Review by AlessioGr — APPROVED** [review]
