### PR TITLE
fix: checks locale is valid for monaco code editor

### LINKED ISSUE #2116: 404 when downloading Code editor assets in Polish dashboard
I recently updated my payload installation to the latest version and noticed that the code editor stopped working. Apparently the scripts that monaco-react fetches from the CDN have a i18n lang identifier in them and this causes https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/editor/editor.main.nls.pl.js to fail with HTTP 404.

Is there any way to force monaco locale? I've tried adding
```typescript
loader.config({ 'vs/nls': { availableLanguages: { '*': 'en' } } });
```
to the top of my `payload.config.ts` but looks like it's being overridden by https://github.com/payloadcms/payload/blob/fa32c2771637af11d7ef0fb21b2f1f3cceae1ead/src/admin/components/utilities/I18n/index.tsx#L21

Here's my minimal repro https://github.com/klapec/payload-monaco-locale (forced Polish locale by setting `i18n.lng: 'pl'`.)

### PR DESCRIPTION
**Pull request by JessRynkar**
## Description

Fixes #2116 

Checks locale is supported by Monaco Editor otherwise returns the default.

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: src/admin/utilities/getSupportedMonacoLocale.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+export const getSupportedMonacoLocale = (locale: string): string => {
+  const supportedLocales = {
```
Comment (DanRibbens) [inline src/admin/utilities/getSupportedMonacoLocale.ts:2]: Where did you find this list of supported lanagues so we can maintain it in the future?

**Review by DanRibbens — APPROVED** [review]
