### PR TITLE
fix: unpublish updates existing version instead of creating a new one

### LINKED ISSUE #10838: What's the point of the unpublish button?
# Documentation Issue

I read [this section](https://payloadcms.com/docs/versions/drafts#unpublishing-drafts) of the doc about drafts but I am still missing a piece of the puzzle: what's the point of unpublishing a content?

## Additional Details

1. My mobile app is fetching only published content (`draft: false`)
2. I accidentally publish a content in payloadcms (which could now be fetched by my mobile app)
3. I click on "`Unpublish`" to revert my content to draft state
4. This action simply duplicate the content in a new version with `draft` status, but the version I accidentally published is still being fetched by the mobile app.

I was expecting this button to revert the status of the current version back to `draft` instead of keeping the `published` version in the history.

- **Am l missing something?** 
- **How can I unpublish a content if I published it by mistake (so no client can fetch this content)?**

Image

### PR DESCRIPTION
**Pull request by GermanJablo**
## Summary

Unpublishing a document currently creates a new version in the versions table, even though the content hasn't changed. Only `_status` transitions from `published` to `draft`. This clutters the version history with redundant entries and has been a source of confusion (see #10838, #12342, #15125).

This PR makes unpublish update the latest existing version in-place instead of creating a new one, for both collections and globals.

Closes #10838 (again)

## Related

#10838
#12342
#15125 (Discussion)

## Changes

- `saveVersion` now accepts an `unpublish` flag. When set, it finds the latest version and updates it in-place (same pattern as the existing autosave overwrite path) instead of creating a new version.
- Collection and global update operations pass `unpublish: unpublishAllLocales` to `saveVersion`.

No UI or `next` package changes are needed. The admin UI already sends `unpublishAllLocales=true` in the query string when the user clicks "Unpublish." This parameter already flowed through the endpoint handler, the operation, and into `updateDocument`. The only thing missing was that `saveVersion` didn't use it. This PR makes `saveVersion` check for it.

For normal updates (saving drafts, publishing, editing content), `unpublishAllLocales` is `undefined`, so `!!undefined` evaluates to `false` and the new code path is skipped entirely.

## Scope and limitations

This PR covers the main "Unpublish" action, which sends `unpublishAllLocales=true` even for non-localized collections. This is the case reported in #10838 and #12342.

Single-locale unpublish (the "Unpublish in [locale]" button, available when `localizeStatus` is enabled) is **not** covered by this PR. That flow does not send `unpublishAllLocales=true`. Instead, it falls into the single-locale publish/unpublish code path, which involves data merging and snapshots. The current code does not distinguish between "publish locale X" and "unpublish locale X," so fixing it requires a new flag (e.g. `unpublishLocale`) that the UI would need to send. This should be addressed in a follow-up PR.

## Testing

Run the new tests with:

```
PAYLOAD_DATABASE=postgres pnpm run test:int versions -- --testNamePattern="Unpublish"
```

Without this PR's changes, 2 of the 3 tests fail:

```
FAIL  should not create a new version when unpublishing a collection document
AssertionError: expected [ { id: 249, parent: 24, …(6) }, …(1) ] to have a length of 1 but got 2

FAIL  should not create a new version when unpublishing a global
AssertionError: expected [ …(2) ] to have a length of 1 but got 2
```

The third test (`should update main table _status to draft when unpublishing`) passes both before and after, confirming the main table was already updated correctly.

### CODE REVIEW

File: packages/payload/src/globals/operations/update.ts [hunk 1]
```diff
@@ -379,6 +379,7 @@ export const updateOperation = async <
         req,
         select,
         snapshot: snapshotToSave,
+        unpublish: unpublishAllLocales,
```
Comment (GermanJablo) [inline packages/payload/src/globals/operations/update.ts:382]: Clarification of something that was confusing for me:

> The naming is admittedly confusing. unpublishAllLocales was introduced for the localizeStatus feature (where each locale can be independently published/unpublished). But the UI sends it as true even for non-localized collections. It effectively means "this is an unpublish operation." That's why I named the parameter unpublish (not unpublishAllLocales) in saveVersion — to make the intent clearer at that level.

File: packages/payload/src/versions/saveVersion.ts [hunk 2]
```diff
@@ -67,6 +69,67 @@ export async function saveVersion<TData extends JsonObject = JsonObject>({
   }
 
   try {
+    if (unpublish) {
```
Comment (JarrodMFlesch) [inline packages/payload/src/versions/saveVersion.ts]: This block of code is the same as the find latest version code below it. Should we make that a helper function?

Comment (GermanJablo) [reply packages/payload/src/versions/saveVersion.ts]: the two blocks are almost identical. The only difference is the condition for updating: unpublish always updates the latest version, while autosave only updates it if the latest version has `autosave: true`. I created #15986 with a `findAndUpdateLatestVersion` helper that takes a `shouldUpdate` callback to handle this. I do not have strong opinions on whether it is cleaner, but it is there if you want to take a look.

Comment (GermanJablo) [reply packages/payload/src/versions/saveVersion.ts]: @JarrodMFlesch I've merged #15986 into this PR. Here's a summary of what changed since my initial version:

**Extracted `updateLatestVersion` helper** (`packages/payload/src/versions/updateLatestVersion.ts`)

The new helper takes a `shouldUpdate` callback that defaults to `() => true`, so the unpublish case doesn't need to pass it at all.

**Removed `createNewVersion` flag**

The old code used a `createNewVersion` boolean (starting as `true`, set to `false` if an overwrite happened). This meant the overwrite result had to be checked and two variables reassigned in a repeated block. Now the flow is simpler: `updateLatestVersion` returns the result directly (or `undefined` if no update was performed), and `!result` drives whether to create a new version. A `createdNewVersion` flag is set only inside the create path, used later for `enforceMaxVersions`.

**Comment by JarrodMFlesch** [comment]
So the only outstanding comment I have is related to the actual impact here. Now when you unpublish a document, it will not have the "paper trail" that it was previously published. I think this is an okay trade off, I just want to call it out here.

**Review by JarrodMFlesch — APPROVED** [review]
