### PR TITLE
fix: Skip parsing if operator is 'exist'

### LINKED ISSUE #5382: Server error when trying to filter collection by 'exists' operator on a field with type 'date'
### Link to reproduction

_No response_

### Describe the Bug

Server error when trying to filter collection by 'exists' operator on a field with type 'date'
```
11:46:51] ERROR (payload): TypeError: Cannot destructure property 'operator' of '(0 , _sanitizeQueryValue.sanitizeQueryValue)(...)' as it is undefined.
    at buildSearchParam (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/@payloadcms/db-mongodb/src/queries/buildSearchParams.ts:97:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseParams (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/@payloadcms/db-mongodb/src/queries/parseParams.ts:60:35)
    at async buildAndOrConditions (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/@payloadcms/db-mongodb/src/queries/buildAndOrConditions.ts:29:22)
    at async parseParams (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/@payloadcms/db-mongodb/src/queries/parseParams.ts:43:33)
    at async buildAndOrConditions (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/@payloadcms/db-mongodb/src/queries/buildAndOrConditions.ts:29:22)
    at async parseParams (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/@payloadcms/db-mongodb/src/queries/parseParams.ts:43:33)
    at async buildAndOrConditions (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/@payloadcms/db-mongodb/src/queries/buildAndOrConditions.ts:29:22)
    at async parseParams (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/@payloadcms/db-mongodb/src/queries/parseParams.ts:43:33)
    at async Function.buildQuery (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/@payloadcms/db-mongodb/src/queries/buildQuery.ts:43:22)
    at async Object.find (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/@payloadcms/db-mongodb/src/find.ts:39:17)
    at async find (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/payload/src/collections/operations/find.ts:145:16)
    at async findHandler (/Users/ivanvasyliev/Documents/Proj/payload_test/payload-test/node_modules/payload/src/collections/requestHandlers/find.ts:30:20)
```

### To Reproduce

1. Create a new Payload app with create-payload-app
2. Open page of any collection that has field with 'date' type
3. Set a filter with parameters: field: *field with 'date' type*, operator: 'exists', value: true or false

### Payload Version

2.11.2

### Adapters and Plugins

_No response_

### LINKED ISSUE #5386: Filters can crash Admin UI
### Link to reproduction

_No response_

### Describe the Bug

When selecting certain Filters in a certain order, I can crash the admin panel.

#### Crash the pannel

I've opened a filters in admin panel selected `exist` : `true` for a calendar field, then changed to `is Greather Then`
Which makes the admin UI crash and we have to manually reload it again.

https://github.com/payloadcms/payload/assets/87857953/8174db7c-1d05-44cf-9a1a-773d903bfe32

#### End in a hanging loading loop

If I use a exists filter on a date field this adds following query to url
`where%5Bor%5D%5B0%5D%5Band%5D%5B0%5D%5BupdatedAt%5D%5Bexists%5D=true`

Filters are set as follows: `exist` : `true` for a calendar field
Then reloading the page including the query results in a broken forever loading content.

https://github.com/payloadcms/payload/assets/87857953/6c991b0a-6b21-4175-b17d-7472234eaccd

### To Reproduce

-

### Payload Version

 "payload": "^2.11.2"

### Adapters and Plugins

```
"@payloadcms/bundler-webpack": "^1.0.6", 
"@payloadcms/db-mongodb": "^1.4.3", 
"@payloadcms/plugin-cloud-storage": "^1.1.2", 
"@payloadcms/plugin-sentry": "^0.0.6",
"@payloadcms/richtext-lexical": "^0.7.0",
```

### PR DESCRIPTION
**Pull request by SimYunSup**
## Description

Fix #5386
Fix #5382 

This bug is because of parsing date logic. So I insert skip logic if operator is `'exists'`.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/db-mongodb/src/queries/sanitizeQueryValue.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ export const sanitizeQueryValue = ({
     formattedValue = Number(val)
   }
 
-  if (field.type === 'date' && typeof val === 'string') {
+  if (field.type === 'date' && typeof val === 'string' && operator !== 'exists') {
```
Comment (lukyfebrianto) [inline packages/db-mongodb/src/queries/sanitizeQueryValue.ts:65]: It seems the problem is not on the `operator` but on the value instead, any boolean string should be cast to boolean type.

Comment (SimYunSup) [reply packages/db-mongodb/src/queries/sanitizeQueryValue.ts:65]: `Boolean` state is used when `field.type` is `checkbox` and when operator is `exists`. It is work when `field.type` is `checkbox`.

But not when operator is `exists` and `field.type` is `date`. Because conditional logic you reviewed is parsing to Date early and return `undefined` when value is not available to parse Date object.

So I change to skip conditional logic when operator is `exists`. I thought about moving the conditional logic for `exists` back to before Date parsing, but that would cause bugs, so I went with this approach.
