### PR TITLE
fix: WhereBuilder component does not accept all valid Where queries

### LINKED ISSUE #3082: Filter state out of sync when loading a collection URL with search params
### Link to reproduction

/admin/collections/widgets?where[tenant][equals]=example

### To Reproduce

Filter state out of sync: `/admin/collections/widgets?where[tenant][equals]=example` 
Works as expected: `/admin/collections/widgets?where[or][0][and][0][tenant][equals]=example`

### Describe the Bug

Changing the filters on a collection page updates the URL, that is great. The URL is a little more complex than needed though. And when linking to a filtered collection in a simple way, breaks the filter state: the collection is filtered, but the UI does not indicate that a filter is active which is confusing.

### Payload Version

1.11.3

### PR DESCRIPTION
**Pull request by AlessioGr**
## Description

Fixes #3082. This update brings both enhanced validation and additional flexibility to Where queries passed into the WhereBuilder from the URL search query params (the filter in the admin panel), while also adding valuable jsDocs for clarity.

Improvements:

- The `validateWhereQuery` function has been reinforced to catch and reject any malformed or nonsensical queries that previously could cause errors.
- Simplified Where queries are now supported. Queries such as `where[text][equals]=example%20post`, which do not fit the [or][and] format, were previously causing errors. The newly introduced `transformWhereQuery` function elegantly handles such queries, transforming them to fit the [or][and] constraints required by the component.

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by AlessioGr** [comment]
One thing we could also do now is to make sure that the query is always simplified in the URL, by using a [simplifyWhereQuery](https://gist.github.com/AlessioGr/7af8ad7d9ec5a9d9578003f33311dd04) function. This will keep URLs simple and easier to understand.

The more complex, forced `or[]and[] `format can then only be used internally.

I don't know if that's a good idea, though. I also do not understand the way the current search query params are updated here: https://github.com/payloadcms/payload/blob/fix/3082/src/admin/components/elements/WhereBuilder/index.tsx#L106

Why do we care about the existing `where` params in the URL, which are merged with the new ones in `newWhereQuery`? And what's the deal with `paramsToKeep`? @jmikrut maybe you can give some input regarding that (& if that's a good idea to do in the first place)

**Comment by DanRibbens** [comment]
Does this also address https://github.com/payloadcms/payload/discussions/2905? After reading the code, it seems like it would.

**Comment by AlessioGr** [comment]
> Does this also address #2905? After reading the code, it seems like it would.

Yep! This would also be addressed with this PR.

File: src/admin/components/elements/WhereBuilder/index.tsx [hunk 1]
```diff
@@ -59,16 +64,28 @@ const WhereBuilder: React.FC<Props> = (props) => {
...
 
+  // This handles initializing the where conditions from the search query (URL). That way, if you pass in
+  // query params to the URL, the where conditions will be initialized from those and displayed in the UI.
+  // Example: /admin/collections/posts?where[or][0][and][0][text][equals]=example%20post
   const [conditions, dispatchConditions] = useReducer(reducer, params.where, (whereFromSearch) => {
-    if (modifySearchQuery && validateWhereQuery(whereFromSearch)) {
-      return whereFromSearch.or;
-    }
+    if (modifySearchQuery && whereFromSearch) {
+      if (validateWhereQuery(whereFromSearch)) {
```
Comment (jacobsfletch) [inline src/admin/components/elements/WhereBuilder/index.tsx:72]: Validating the where query here seems unnecessary, couldn't you just simply transform it? The transformer function will ensure it's returned in the correct format no matter what. No extra validation needed.

File: src/admin/components/elements/WhereBuilder/index.tsx [hunk 2]
```diff
@@ -15,6 +15,7 @@ import { Where } from '../../../../types';
 import { getTranslation } from '../../../../utilities/getTranslation';
 
 import './index.scss';
+import { transformWhereQuery } from './transformWhereQuery';
```
Comment (jacobsfletch) [inline src/admin/components/elements/WhereBuilder/index.tsx:18]: Need to sort this import

File: src/admin/components/elements/WhereBuilder/index.tsx (hunk 1 above)
Comment (AlessioGr) [reply src/admin/components/elements/WhereBuilder/index.tsx:72]: @jacobsfletch So, I have tried experimenting with removing that validate and ALWAYS transforming those `where` queries.

The problem here is, that for a valid where query, it would result in additional map operations in the transform step. With that additional validate step, we can skip the unnecessary transform for valid where queries, which will improve the performance. And valid where queries will happen a lot more common than invalid ones anyways.

I'd thus vote for keeping it this way
