### PR TITLE
fix: enables locales with date field

### LINKED ISSUE #1964: Date picker isn't localized
# Bug Report

I created a basic `type: "date"` field and my project implements localization for both the API and the Admin UI. However, the Admin UI doesn't localize the date picker that pops up from the Date input field. It always displays in English even when the user has the language set to another some other one.

## Steps to Reproduce

1. Create any collection or global with a basic `type: "date"` field.
2. Run the Admin UI and change your user's language to Spanish.
3. Click on the date field to view the Popover with the date picker. It will still be in English.

## Other Details

I don't know how to fix the issue inside the Payload source code, but I understand you're using the `react-datepicker` component, which does support the `locale` property. I'm sure it should be an easy thing to solve. [Docs for the `locale` prop from `react-datepicker`](https://reactdatepicker.com/#example-locale)

Update: Actually, the formatted date displayed all around the Admin UI isn't localized either. It's always displayed in English. I believe this could also be solved using locales with `date-fns` or `dayjs`.

### PR DESCRIPTION
**Pull request by JessRynkar**
## Description

#1964 

Enables localization on react-datepicker within date field.

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: src/admin/components/elements/DatePicker/formattedLocales.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
+// Locales must match the locales from date-fns
+// https://github.com/date-fns/date-fns/blob/main/src/locale/
+
+export const formattedLocales = {
```
Comment (DanRibbens) [inline src/admin/components/elements/DatePicker/formattedLocales.ts:4]: Can we change this so we import from src/translations/index, use Object.keys(translations), then overwrite the few that need to be directly changed?

This will make it one place to change the file when a new translation gets added where the datepicker already supports the same language code. There is an acceptable (in my mind) risk with this in that new langauges will need to be tested or checked against the supported languages of tnhe datepicker.

File: src/admin/components/elements/DatePicker/DatePicker.tsx [hunk 2]
```diff
@@ -26,6 +35,16 @@ const DateTime: React.FC<Props> = (props) => {
     placeholder: placeholderText,
   } = props;
 
+  let currentLocale = useLocale();
+  currentLocale = formattedLocales[currentLocale] || currentLocale;
```
Comment (DanRibbens) [inline src/admin/components/elements/DatePicker/DatePicker.tsx:39]: This is very clean, I like it!

**Review by DanRibbens — APPROVED** [review]
Thanks for making the changes, this looks great!

File: src/admin/components/elements/DatePicker/DatePicker.tsx (hunk 2 above)
Comment (JessChowdhury) [reply src/admin/components/elements/DatePicker/DatePicker.tsx:39]: Thanks Dan!
