### PR TITLE
fix(db-mongodb): add ability to disable fallback sort and no longer adds a fallback for unique fields

### LINKED ISSUE #12690: [Performance] Regression since 3.39.0 on Large Collection 10M+ mongoDb
### Describe the Bug

hi,

i just upgraded from 3.33 to latest 3.40.0, i found performance regression on large mongodb collection with a relationship, its  just not loading in UI, its taking 120+ seconds to show the records sometime not at all.

i tested downgrading payload version i found the issue started occurring since 3.39.0.

issue with a large collection with 38M records , the collection have a single relationship with another collection , 
```
{
      name: 'categories',
      type: 'relationship',
      relationTo: 'product-categories',
      hasMany: true,
     
    },
```

i have another large collection with 229M records it loads fine as it doesn't have any relationship, it seems how relationships are pulled has changed.

i am using payload since v1 never had any issue like this ever.

### Link to the code that reproduces this issue

kindly suggest how to make a reproduction for this

### Reproduction Steps

to reproduce make a collection with about 10M records having a relationship like this (see below) , product-categories collection  just have about 3000 records. try to load the collection in backend it will just not load or take a lot of time , compare same with payload 3.38.0 it works perfectly .

kindly suggest how to make a reproduction for this?

relationship field
```
{
      name: 'categories',
      type: 'relationship',
      relationTo: 'product-categories',
      hasMany: true,
     
   }
```

### Which area(s) are affected? (Select all that apply)

db-mongodb, area: ui

### Environment Info

```text
Binaries:
  Node: 22.11.0
  npm: 11.2.0
  Yarn: 1.22.22
  pnpm: 10.6.5
Relevant Packages:
  payload: 3.39.0
  next: 15.3.0
  @payloadcms/db-mongodb: 3.39.0
  @payloadcms/email-nodemailer: 3.39.0
  @payloadcms/graphql: 3.39.0
  @payloadcms/next/utilities: 3.39.0
  @payloadcms/payload-cloud: 3.39.0
  @payloadcms/plugin-seo: 3.39.0
  @payloadcms/richtext-lexical: 3.39.0
  @payloadcms/translations: 3.39.0
  @payloadcms/ui/shared: 3.39.0
  react: 19.0.0
  react-dom: 19.0.0
Operating System:
  Platform: linux
  Arch: x64
  Version: #59-Ubuntu SMP PREEMPT_DYNAMIC Sat Mar 15 17:40:59 UTC 2025
  Available memory (MB): 112478
  Available CPU cores: 12
```

### PR DESCRIPTION
**Pull request by paulpopus**
You can now disable fallback sort in the mongodb adapter by passing `disableFallbackSort: true` in the options.

We also no longer add fallback sort to sorts on unique fields by default now.

This came out of a discussion in this issue https://github.com/payloadcms/payload/issues/12690
and the linked PR https://github.com/payloadcms/payload/pull/12888

Closes https://github.com/payloadcms/payload/issues/12690

### CODE REVIEW

File: packages/db-mongodb/src/queries/buildSortParam.ts [hunk 1]
```diff
@@ -150,6 +150,12 @@ export const buildSortParam = ({
     sort = [sort]
   }
 
+  // We use this flag to determine if the sort is unique or not to decide whether to add a fallback sort.
+  const isUniqueSort = sort.every((item) => {
+    const field = getFieldByPath({ fields, path: item })
+    return field?.field?.unique
+  })
+
```
Comment (r1tsuu) [inline packages/db-mongodb/src/queries/buildSortParam.ts]: Shouldn't this be `some` instead?
Imagine I sort by like:
`['name', 'email']` - `name` isn't `unique` but `email` is
Do I need here another fallback, if `email` is `unique: true`? With your logic it'd add a fallback.

**Review by r1tsuu — CHANGES_REQUESTED** [review]
Just one question:

**Review by r1tsuu — APPROVED** [review]

**Comment by fturmel** [comment]
Thanks for the fix! As I pointed out on Discord a few days ago this also completely broke CosmosDB compat (missing indices are fatal, and it created the need for _tons_ of manually created compound indices for the UI to work).

Is there a need for additional documentation on how to configure the mongoose adaptor for CosmosDB? It seems like we'll need to set `disableFallbackSort: true` explicitly.

https://payloadcms.com/docs/database/mongodb#using-other-mongodb-implementations
https://payloadcms.com/docs/production/deployment#cosmosdb (btw - no mention here that you need to also set `transactionOptions: false` for CosmosDB)

**Comment by paulpopus** [comment]
> Is there a need for additional documentation on how to configure the mongoose adaptor for CosmosDB?

@fturmel probably yes. But there's another, bigger PR that aims to fix many issues and incompatibilities there so it's probably better fitted for that PR or after it

**Comment by fturmel** [comment]
> @fturmel probably yes. But there's another, bigger PR that aims to fix many issues and incompatibilities there so it's probably better fitted for that PR or after it

Perfect! I'll be watching progress there too (I presume it's #12763). Thanks for the great work everyone.
