### PR TITLE
Fix/#1442 reactive relationship select

### LINKED ISSUE #1442: hasMany relationship field not rendering correctly on UI field dispatch
# Bug Report

I have two fields set up in a 'Creations' Collection like so:

```
{
      type: "ui",
      name: "creationIngredientDefaults",
      admin: {
        components: {
          Field: CreationIngredientDefaults,
        },
      },
    },
    {
      name: "ingredients",
      type: "relationship",
      relationTo: "ingredients",
      hasMany: true,
    },
```

In the 'CreationIngredientDefaults' component, I have the following code which updates the state of the 'ingredients' field:

```
const ingredients = useFormFields(([fields, dispatch]) => ({ fields, dispatch }));

    const select = async (type: string) => {
        const newValue = [...creationComponents.common, ...creationComponents[type]];
        ingredients.dispatch({ type: 'UPDATE', path: 'ingredients', value: newValue })
    }
```

## Current Behavior

The ingredients field is updated with all of the new array values, but not all of them are being displayed in the Ingredients field UI. There are 10 values in the array, but only 2 are displayed.

- If I console.log the value of the ingredients field, it does have 10 values.
- If I try to add one of the missing array values again, it does not show up in the list of options (which is the expected behaviour)

## Expected Behavior

I would expect all 10 array values to appear in the Relationship field UI.

## Steps to Reproduce

Here is the code for my CreationIngredientDefaults component:

```
import React from 'react';
import { useFormFields, useAllFormFields } from 'payload/components/forms'
import { FieldAction } from 'payload/dist/admin/components/forms/Form/types';
import './style.scss';

const creationComponents = {
    common: [
        "6361029a1632ca197eb60b1f",
        "636102941632ca197eb609b7",
        "636102981632ca197eb60a8b",
        "636102941632ca197eb609c3",
        "6361029a1632ca197eb60b1b",
        "636102981632ca197eb60a93",
        "636102941632ca197eb609c7",
        "636102911632ca197eb6090f",
        "636102961632ca197eb60a1f",
    ],
    'option-1': [
        '636102961632ca197eb60a13',
    ],
    'option-2': [
        '636102961632ca197eb60a17',
    ],
    'option-3': [
        '636102961632ca197eb60a13',
        '636102961632ca197eb60a17',
        '636102981632ca197eb60a97',
    ],
    'option-4': [
        '636102961632ca197eb60a17',
        '636102981632ca197eb60a97',
        '636102991632ca197eb60acf',
    ]
}

const Field: React.FC = () => {
    const ingredients = useFormFields(([fields, dispatch]) => ({ fields, dispatch }));

    const select = async (type: string) => {
        const newValue = [...creationComponents.common, ...creationComponents[type]];
        ingredients.dispatch({ type: 'UPDATE', path: 'ingredients', value: newValue })
    }
    const options = [{
        key: 'option-1',
        label: 'Option 1'
     },{
        key: 'option-2',
        label: 'Option 2'
     },{
        key: 'option-3',
        label: 'Option 3'
     },{
        key: 'option-4',
        label: 'Option 4'
     }];
    return (
        <>
            <div className="default-ingredients-button-wrapper">
                <p className="default-ingredients-helper-text">Click a button below to automatically select the default ingredients for a creation</p>
                {options.map(o => (
                    <button key={o.key} type="button" onClick={() => select(o.key)} className={`btn ${o.key} btn--icon-style-without-border btn--size-small btn--icon-position-right`}>{o.label}</button>
                ))}
            </div>
        </>
    )
}

export default Field;
```

The values in the 'creationComponents' arrays are IDs of Ingredient documents in the Ingredients collection.

CleanShot_2022-11-17_at_14 51 272x
CleanShot_2022-11-17_at_14 55 212x
CleanShot_2022-11-17_at_14 53 332x

### PR DESCRIPTION
**Pull request by JarrodMFlesch**
## Description

Fixes #1442 
Populates relationship pills in select when added via form context.

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/admin/components/forms/field-types/Relationship/index.tsx [hunk 1]
```diff
@@ -277,79 +209,64 @@ const Relationship: React.FC<Props> = (props) => {
...
-      setHasLoadedValueOptions(false);
-      getResults({
-        value: initialValue,
-      });
-    }
-  }, [initialValue, getResults, optionFilters, filterOptions]);
+      }
+    }, Promise.resolve());
+  }, [
+    options,
```
Comment (jacobsfletch) [inline src/admin/components/forms/field-types/Relationship/index.tsx:259]: `options` as a dependency here is throwing this effect into an infinite loop because it's being reset on lines 251 and 253.

Comment (jacobsfletch) [reply src/admin/components/forms/field-types/Relationship/index.tsx]: I was able to remove that dependency from the effect by moving the logic into the `optionsReducer`, where `state` replaces `options`. See this commit: https://github.com/payloadcms/payload/commit/54ef40a335905f7295f847c68762f7fe06bccc30

**Review by DanRibbens — COMMENTED** [review]
SO article about useReducer async state updates: https://stackoverflow.com/questions/53146795/react-usereducer-async-data-fetch
