### PR TITLE
fix: timestamp queries

### LINKED ISSUE #2582: Local API Query Error updatedAt / createdAt
### Link to reproduction

https://github.com/edtorba/payload

### To Reproduce

Use local API query - can be any operation, find, find by, delete, so on.

Within your query add where clause for `createdAt` or `updatedAt` properties.

e.g.
```js
const tenMinutesAgo = new Date(Date.now() - 1000 * 60 * 10);
// ...
where: {
  createdAt: {
    less_than_equal: tenMinutesAgo,
  },
},
```
Expected result: successful run.
Actual result: `QueryError: The following path cannot be queried: createdAt` (& `updatedAt`)

Failing test can be found [here](https://github.com/edtorba/payload/blob/master/test/_community/int.spec.ts)

### Describe the Bug

Have noticed when upgraded to 1.7.2 from 1.6.28 version. Relatively straight forward bug. Not much can be added here to describe it further.

### Payload Version

1.7.2

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

fixes #2582
I fixed the issue by injecting createdAt and updatedAt fields during config sanitization. I was going to have to also push them in buildQuery and getEntityPolicies. Instead I eliminated redundancy where we were pushing those same fields in many places which should help avoid future bugs. 

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: src/collections/config/sanitize.ts [hunk 1]
```diff
@@ -23,6 +30,42 @@ const sanitizeCollection = (config: Config, collection: CollectionConfig): Sanit
     isMergeableObject: isPlainObject,
   });
 
+  if (sanitized.timestamps !== false) {
+    let hasUpdatedAt = null;
+    let hasCreatedAt = null;
+    let i = 0;
+    while (hasCreatedAt === null && hasUpdatedAt === null && i < sanitized.fields.length) {
```
Comment (JarrodMFlesch) [inline src/collections/config/sanitize.ts:37]: _Should_ this be a while loop? I feel like a for loop would make more sense.

It seems like you would want to loop over all fields to check for _both_ `createdAt` and `updatedAt`. In this case, the loop will break when one of them is found and will not keep checking for the other.

I also wonder if we should be setting these fields `require: true` here instead of [here](https://github.com/payloadcms/payload/pull/2583/files#diff-1ea0586c0f08570bb5ba4938494ccaa6cdf35a0975ed7a51cacf73f5ab8ffb4bR409).

Comment (DanRibbens) [reply src/collections/config/sanitize.ts:37]: You're right, my while loop condition is wrong. I used a while loop to stop iterating fields once createdAt and updatedAt were taken care of. I'll fix the condition.

The fields can't be `required` for the admin UI or the backend because of validation. The only reason I used `required: true` in entityToJSONSchema is for type generation. In the type they are always defined.
