### PR TITLE
fix: prevents row overflow and fixes margin

### LINKED ISSUE #4697: Admin panel media upload field long title out of bounds
### Link to reproduction

_No response_

### Describe the Bug

I have created a custom content field: 
` {
        name: 'media',
        type: 'upload',
        relationTo: 'media',
        required: true,
      },
 `
 Works good, as intended, but when uploading media with a really long name (like in picture), file name do not break and goes out of content editor bounds. 
 
image

 To test further, I have changed file name to be even longer, with this change, name goes beyond the screen.

image

Tested with default Media Block and text is cropped
image

### To Reproduce

Field used to upload media:

```
import type { Field } from 'payload/types'

type UploadType = (options?: { disableLabel?: boolean }) => Field

export const iconField: UploadType = () => {
  const uploadResult: Field = {
    type: 'row',
    fields: [
      {
        name: 'iconAlign',
        label: 'Align',
        type: 'select',
        defaultValue: 'default',
        options: [
          {
            label: 'Default',
            value: 'default',
          },
          {
            label: 'Start',
            value: 'start',
          },
          {
            label: 'Center',
            value: 'center',
          },
          {
            label: 'End',
            value: 'end',
          },
        ],
      },
      {
        name: 'iconSize',
        label: 'Size',
        type: 'select',
        defaultValue: 'medium',
        options: [
          {
            label: 'Small',
            value: 'small',
          },
          {
            label: 'Medium',
            value: 'medium',
          },
          {
            label: 'Large',
            value: 'large',
          },
        ],
      },
      {
        name: 'media',
        type: 'upload',
        relationTo: 'media',
        required: true,
      },
    ],
  }

  return uploadResult
}

```
Payload-types.ts for this field:

```
icon: {
  align?: 'default' | 'start' | 'center' | 'end'
  size: 'small' | 'medium' | 'large'
  media: string | Media
  id?: string
  blockName?: string
  blockType: 'iconBlock'
}
```

Used versions:
```
@next/eslint-plugin-next@13.5.6
@payloadcms/bundler-webpack@1.0.5
@payloadcms/db-mongodb@1.1.0
@payloadcms/eslint-config@0.0.1
@payloadcms/plugin-cloud@2.2.6
@payloadcms/plugin-nested-docs@1.0.9
@payloadcms/plugin-redirects@1.0.1
@payloadcms/plugin-seo@1.0.15
@payloadcms/richtext-slate@1.3.1
@swc/core@1.3.76
@types/escape-html@1.0.4
@types/express@4.17.21
@types/node@18.11.3
@types/qs@6.9.10
@types/react@18.0.21
@typescript-eslint/eslint-plugin@5.62.0
@typescript-eslint/parser@5.62.0
copyfiles@2.4.1
cross-env@7.0.3
dotenv@8.6.0
escape-html@1.0.3
eslint-config-prettier@8.10.0
eslint-import-resolver-alias@1.1.2
eslint-plugin-filenames@1.3.2
eslint-plugin-import@2.25.4
eslint-plugin-prettier@4.2.1
eslint-plugin-react-hooks@4.6.0
eslint-plugin-simple-import-sort@10.0.0
eslint@8.55.0
express@4.18.2
next@13.5.2
nodemon@2.0.22
payload-admin-bar@1.0.6
payload@2.4.0
prettier@2.8.8
qs@6.11.2
react-dom@18.2.0
react-hook-form@7.45.4
react-router-dom@5.3.4
react@18.2.0
slate@0.91.4
ts-node@10.9.1
typescript@4.9.5
```

### Payload Version

2.4.0

### Adapters and Plugins

_No response_

### PR DESCRIPTION
**Pull request by JessRynkar**
## Description

Closes #4697. Fixes overflow and squashed margins with row field.

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.
- 
Before:
Screenshot 2024-01-05 at 1 58 22 PM

After:
Screenshot 2024-01-05 at 1 58 52 PM

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](https://github.com/payloadcms/payload/tree/main/templates) directory (does not affect core functionality)
- [ ] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)
- [ ] This change requires a documentation update

### CODE REVIEW

File: packages/payload/src/admin/components/forms/field-types/Row/index.tsx [hunk 1]
```diff
@@ -34,7 +34,7 @@ const Row: React.FC<Props> = (props) => {
           fieldTypes={fieldTypes}
           forceRender={forceRender}
           indexPath={indexPath}
-          margins={false}
+          margins="small"
```
Comment (jacobsfletch) [inline packages/payload/src/admin/components/forms/field-types/Row/index.tsx:37]: This change is questionable. Need to test this in other places to check for unintended consequences.

Comment (JessChowdhury) [reply packages/payload/src/admin/components/forms/field-types/Row/index.tsx]: Reverted now

**Review by jacobsfletch — APPROVED** [review]
