### PR TITLE
fix: avoids getting and setting doc preferences when creating new

### LINKED ISSUE #5739: initCollapsed not always respected when collapsible is inside of array
### Link to reproduction

https://github.com/franciscolourenco/payload/commits/reproduce-collapsibe-inside-array-initCollapsed-not-respected/

### Describe the Bug

When a collapsible field is used inside of an array field, the `initCollapsed` option is not always respected. Particularly, after preferences have been saved for the array, but preferences for the specific collapsible have not been saved.

### To Reproduce

1. Create array item
2. Expand collapsible inside array item
3. Collapse collapsible inside array item
4. Create new array item
5. Verify that the new collapsible is unexpectedly expanded
6. The same happens for new array item is created afterwards

https://github.com/payloadcms/payload/assets/208149/1767c6de-269e-4d12-8d94-8b441cfddb73

### Payload Version

2.12.1 (latest main)

### Adapters and Plugins

_No response_

### LINKED ISSUE #5747: UI state shouldn't be remembered in new document view.
### Link to reproduction

https://github.com/franciscolourenco/payload/commit/b0bce9f19b1e1058bcc59f4f784eb8addfcbbc12

### Describe the Bug

The UI state of some fields, like Tabs, Collapsibles, Arrays is currently being saved in the preferences. My understanding is that this is unintended in the new document view. 

https://github.com/payloadcms/payload/assets/208149/40762bf8-d5e0-4c08-b465-a15147beb6c7

### To Reproduce

1. `pnpm dev _community`
2. Open the new Post view
3. Select the second tab
4. Save the new Post
5. Create a new Post
6. Verify that the second tab is now selected, instead of the first as it would be expected.

### Payload Version

2.12.1

### Adapters and Plugins

_No response_

### PR DESCRIPTION
**Pull request by PatrikKozak**
## Description

Fixes #5739 #5747 

fix: only call `getPreferences` & `setPreferences` if preferencesKey exists

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: packages/payload/src/admin/components/forms/field-types/Collapsible/index.tsx [hunk 1]
```diff
@@ -41,33 +41,39 @@ const CollapsibleField: React.FC<Props> = (props) => {
...
-      })
+              }),
+        })
+      }
     },
     [preferencesKey, fieldPreferencesKey, getPreference, setPreference, path],
   )
 
   useEffect(() => {
+    if (!docID) {
```
Comment (jacobsfletch) [inline packages/payload/src/admin/components/forms/field-types/Collapsible/index.tsx:73]: You should check for `preferencesKey` instead

File: packages/payload/src/admin/components/forms/field-types/Collapsible/index.tsx [hunk 2]
```diff
@@ -41,33 +41,39 @@ const CollapsibleField: React.FC<Props> = (props) => {
...
+        })
+      }
     },
     [preferencesKey, fieldPreferencesKey, getPreference, setPreference, path],
   )
 
   useEffect(() => {
+    if (!preferencesKey) {
+      setCollapsedOnMount(typeof initCollapsed === 'boolean' ? initCollapsed : false)
+    }
```
Comment (jacobsfletch) [inline packages/payload/src/admin/components/forms/field-types/Collapsible/index.tsx:75]: You need to also return out of this effect, or add an `else` statement

**Review by jacobsfletch — APPROVED** [review]

**Comment by franciscolourenco** [comment]
Both issues fixed 🎉  thank you 🙏
