### PR TITLE
fix: get external resource blocked

### LINKED ISSUE #12876: storage-s3: Changing uploaded Media fails with "Blocked unsafe attempt" in v3.43.0
### Describe the Bug

s3 storage: Changing an image that has already been uploaded throws the following error: "An error occurred while uploading the file.. Blocked unsafe attempt to http://xxx" in Payload v3.43.0.

Earlier versions are not affected; there is no error after downgrading to version 3.42.

Thanks in advance for checking this out.

### Link to the code that reproduces this issue

pnpx create-payload-app@latest -t website

### Reproduction Steps

These steps are based on the Website template:

1.) Enable the s3 storage plugin:

```js
s3Storage({
      collections: {
        media: true,
      },
      bucket: process.env.S3_BUCKET_NAME || '',
      config: {
        region: process.env.S3_REGION || '',
        endpoint: process.env.S3_ENDPOINT || '',
        credentials: {
          accessKeyId: process.env.S3_ACCESS_KEY || '',
          secretAccessKey: process.env.S3_SECRET_KEY || '',
        },
      },
    }),
```

2) Upload an image to the Media collection – this works without any issues.

3) Edit the image, for example by changing the alt text, and click Save.

4) An error is thrown and the image is not updated. See the error in the logs:

```js
err: {
      "type": "FileRetrievalError",
      "message": "An error occurred while uploading the file.. Blocked unsafe attempt to http://localhost:3020/api/media/file/dummy-upload.png",
...}
```

### Which area(s) are affected? (Select all that apply)

plugin: cloud-storage

### Environment Info

```text
Binaries:
  Node: 20.19.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 10.3.0
Relevant Packages:
  payload: 3.43.0
  next: 15.3.0
  @payloadcms/db-mongodb: 3.43.0
  @payloadcms/email-nodemailer: 3.43.0
  @payloadcms/graphql: 3.43.0
  @payloadcms/live-preview: 3.43.0
  @payloadcms/live-preview-react: 3.43.0
  @payloadcms/next/utilities: 3.43.0
  @payloadcms/payload-cloud: 3.43.0
  @payloadcms/plugin-cloud-storage: 3.43.0
  @payloadcms/plugin-form-builder: 3.43.0
  @payloadcms/plugin-nested-docs: 3.43.0
  @payloadcms/plugin-redirects: 3.43.0
  @payloadcms/plugin-seo: 3.43.0
  @payloadcms/richtext-lexical: 3.43.0
  @payloadcms/storage-s3: 3.43.0
  @payloadcms/translations: 3.43.0
  @payloadcms/ui/shared: 3.43.0
  react: 19.1.0
  react-dom: 19.1.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.5.0: Tue Apr 22 19:53:27 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6041
  Available memory (MB): 24576
  Available CPU cores: 12
```

### PR DESCRIPTION
**Pull request by kendelljoseph**
## Fix
- Use `[Config].upload.skipSafeFetch` to allow specific external urls
- Use `[Config].upload.pasteURL.allowList` to allow specific external urls

Documentation: [Uploading files from remote urls](https://payloadcms.com/docs/upload/overview#uploading-files-from-remote-urls)

Fixes: https://github.com/payloadcms/payload/issues/12876
Mentioned: https://github.com/payloadcms/payload/issues/7037, https://github.com/payloadcms/payload/issues/12934
Source PR: https://github.com/payloadcms/payload/pull/12622
Issue Trace:
1. [`allowList` Added](https://github.com/payloadcms/payload/pull/12622/commits/8b7f2ddbf47fba63be94f0208ca0e1774f60d031#diff-92acf7b8d30e447a791e37820136bcbf23c42f0358daca0fdea4e7b77f7d4bc9
)

2. [`allowList` Removed](https://github.com/payloadcms/payload/pull/12622/commits/648c168f86af4d5790a37e9217da4c1917f7d85c#diff-92acf7b8d30e447a791e37820136bcbf23c42f0358daca0fdea4e7b77f7d4bc9)

### CODE REVIEW

File: packages/payload/src/uploads/getExternalFile.ts [hunk 1]
```diff
@@ -23,11 +24,54 @@ export const getExternalFile = async ({ data, req, uploadConfig }: Args): Promis
...
+            // Allow a specific URL with a port
+            { protocol: 'http', hostname: '127.0.0.1', port: '3000', search: '' },
+            // Allow a local address
+            { protocol: 'http', hostname: 'localhost', port: '3000', search: '' },
+          ],
+        },
+       ```
+     */
+    const allowList = uploadConfig.pasteURL ? uploadConfig.pasteURL.allowList : []
+    let res
```
Comment (denolfe) [inline packages/payload/src/uploads/getExternalFile.ts:40]: Let's type this

File: packages/payload/src/uploads/getExternalFile.ts [hunk 2]
```diff
@@ -23,11 +24,54 @@ export const getExternalFile = async ({ data, req, uploadConfig }: Args): Promis
       ? uploadConfig.externalFileHeaderFilter(Object.fromEntries(new Headers(req.headers)))
       : { cookie: req.headers.get('cookie')! }
 
-    const res = await safeFetch(fileURL, {
-      credentials: 'include',
-      headers,
-      method: 'GET',
-    })
+    /**
+     * `fetch` on the `allowList` in the the upload config.`
```
Comment (denolfe) [inline packages/payload/src/uploads/getExternalFile.ts]: Extra backtick

File: packages/payload/src/uploads/types.ts [hunk 3]
```diff
@@ -225,7 +225,8 @@ export type UploadConfig = {
   /**
    * Controls the behavior of pasting/uploading files from URLs.
    * If set to `false`, fetching from remote URLs is disabled.
-   * If an allowList is provided, server-side fetching will be enabled for specified URLs.
+   * If an `allowList` is provided, server-side fetching will be enabled for specified URLs.
```
Comment (denolfe) [inline packages/payload/src/uploads/types.ts:228]: Let's add more here talking about fetching external files. It's not immediately clear what server-side fetching is referring to if you're looking at this fresh.

**Review by denolfe — CHANGES_REQUESTED** [review]
A few small things should be improved.

Also be sure to add `Fixes #` if this PR fixes any open issues. I see related ones are listed but just wanted to be sure.

Let's run through testing this against real S3 or R2 today.

File: packages/payload/src/uploads/getExternalFile.ts [hunk 4]
```diff
@@ -23,11 +24,54 @@ export const getExternalFile = async ({ data, req, uploadConfig }: Args): Promis
...
+     * Array<{
+          hostname: string
+          pathname?: string
+          port?: string
+          protocol?: 'http' | 'https'
+          search?: string
+        }>
+     *```
+     
+     * Config example:
```
Comment (denolfe) [inline packages/payload/src/uploads/getExternalFile.ts]: Looks like your prettier might not be running either. I'm seeing these changes when I save the file. 

CleanShot 2025-06-25 at 11 28 27@2x

File: packages/payload/src/uploads/types.ts (hunk 3 above)
Comment (kendelljoseph) [reply packages/payload/src/uploads/types.ts:228]: Added `skipSafeFetch`

File: packages/payload/src/uploads/getExternalFile.ts (hunk 1 above)
Comment (denolfe) [reply packages/payload/src/uploads/getExternalFile.ts:40]: Looks like it gets inferred well, enough. Resolving.

File: packages/plugin-cloud-storage/src/plugin.ts [hunk 5]
```diff
@@ -70,6 +70,47 @@ export const cloudStoragePlugin =
...
+              const localhostEntry =
+                process.env.NODE_ENV !== 'production' && !hasExactLocalhostMatch
+                  ? [{ hostname: 'localhost' }]
+                  : []
+
+              return [...existingSkipSafeFetch, ...localhostEntry]
+            }
+
+            if (process.env.NODE_ENV !== 'production') {
+              return [{ hostname: 'localhost' }]
```
Comment (denolfe) [inline packages/plugin-cloud-storage/src/plugin.ts:108]: Should this be adding the `existingSkipSafeFetch` as well when not in production?

Comment (kendelljoseph) [reply packages/plugin-cloud-storage/src/plugin.ts:108]: That case is covered by 
```ts 
// ...
} else if (isAllowListSkipSafeFetch) {
  // ...
  return [...existingSkipSafeFetch, ...localhostEntry]
}
```

This condition is for when there is no list at all.

Since there is no list, there is nothing to add at this point.

Comment (denolfe) [reply packages/plugin-cloud-storage/src/plugin.ts:108]: Ah, yes, I follow 👍
