### PR TITLE
fix: upload editing error with plugin-cloud

### LINKED ISSUE #4141: Editing an image's size in dashboard gives an error
### Link to reproduction

/

### Describe the Bug

When I edit an image it's size after uploading it I get an error saying "Something went wrong". Then in my logs it says this:

`<html>
<body>

[2023-11-14T14:37:46] | (payload): Error: ENOENT: no such file or directory, open '/workspace/payload/dist/images/triton-tx550.jpg'
-- | --
[2023-11-14T14:37:46] | at Object.openSync (node:fs:590:3)
[2023-11-14T14:37:46] | at Object.readFileSync (node:fs:458:35)
[2023-11-14T14:37:46] | at getFileByPath (/workspace/payload/node_modules/payload/dist/uploads/getFileByPath.js:21:34)
[2023-11-14T14:37:46] | at generateFileData (/workspace/payload/node_modules/payload/dist/uploads/generateFileData.js:46:59)
[2023-11-14T14:37:46] | at updateByID (/workspace/payload/node_modules/payload/dist/collections/operations/updateByID.js:103:106)
[2023-11-14T14:37:46] | at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-11-14T14:37:46] | at async updateByIDHandler (/workspace/payload/node_modules/payload/dist/collections/requestHandlers/updateByID.js:35:21)

</body>
</html>`

Sometimes I also get this error while editing the size before uploading/saving. Is this a known issue in Payload or just for me?

To edit the size I use the build in image editor in the dashboard and I use the overlay sliders on the image to make the view smaller.

### To Reproduce

Upload an image in payload dashboard and try to edit it's size after uploading the image. (Sometimes I also get an error while trying to edit it's size while I upload it)

### Payload Version

2.0.13

### Adapters and Plugins

_No response_

### PR DESCRIPTION
**Pull request by JessRynkar**
## Description

- Fixes upload error with cloud plugin when editing a file [#81](https://github.com/payloadcms/plugin-cloud-storage/issues/81)
- Fixes upload preview drawer urls

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] Existing test suite passes locally with my changes

### CODE REVIEW

**Comment by JarrodMFlesch** [comment]
@JessChowdhury 

I am able to get the ui into a problematic state when I check out this branch. All I did was:

1. upload an image and save
2. crop the image and save again

#### API looks like the url hangs around for images that do not actually exist
CleanShot 2023-11-17 at 8  59 25

#### Broken link UI
CleanShot 2023-11-17 at 8  59 13

File: packages/payload/src/admin/components/elements/PreviewSizes/index.tsx [hunk 1]
```diff
@@ -121,12 +122,13 @@ const PreviewSizes: React.FC<{
...
             onClick={() => setSelectedSize(null)}
-            previewSrc={generateImageUrl(doc.filename)}
+            previewSrc={generateImageUrl(doc)}
           />
 
           {Object.entries(orderedSizes).map(([key, val]) => {
             const selected = selectedSize === key
-            const previewSrc = val.filename ? generateImageUrl(val.filename) : undefined
+            const previewSrc = generateImageUrl(val)
+            console.log(previewSrc)
```
Comment (JarrodMFlesch) [inline packages/payload/src/admin/components/elements/PreviewSizes/index.tsx:131]: @JessChowdhury plz remove
