### PR TITLE
fix: allow json field to be saved empty and reflect value changes

### LINKED ISSUE #4575: JSON fields don't show updated value after useField setValue
### Link to reproduction

_No response_

### Describe the Bug

I've created a ui Field with a custom component that's a button to update the contents of a json Field (this is a prototype, eventually, this would fetch data from a Google Sheet).

However, when I click the custom button to trigger a `setValue` from `useField` for the JSON field, the Monaco editor component that Payload uses doesn't seem to refresh to reflect the new value.

### To Reproduce

Create a collection...

```ts
import { CollectionConfig } from 'payload/types';

import SyncButton from '../components/SyncButton';

const defaultSurveyContent = { foo: 123};

export const Surveys: CollectionConfig = {
  slug: 'surveys',
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
    },
    {
      name: 'content',
      type: 'json',
      defaultValue: defaultSurveyContent,
    },
    {
      name: 'syncButton',
      type: 'ui',
      admin: {
        components: {
          Field: SyncButton,
        },
      },
    },
  ],
};
```

...with the following custom UI component:

```tsx
import { Button } from 'payload/components';
import { useField } from 'payload/components/forms';
import React from 'react';

export default function SyncButton() {
  const { value: content, setValue: setContent } = useField<string>({ path: 'content' });

  function syncContent() {
    setContent({ foo: 'bar' });
  }

  return (
    <Button onClick={syncContent} buttonStyle='secondary'>
      Sync Content
    </Button>
  );
}
```

Click the 'Sync content' UI field and the JSON data in the Monaco editor component doesn't change. But if you save the record and reload the page, the JSON value is now `{ "foo": "bar" }`, suggesting the click changed it, but the component just didn't re-render.

This works fine if you use `setValue` on a text field, so this issue seems to be specific to the Monaco editor.

### Payload Version

2.5.0

### Adapters and Plugins

_No response_

### PR DESCRIPTION
**Pull request by JessRynkar**
## Description

Closes #4575

- Reflects updated value/JSON in the Monaco editor
- Fixes JSON field not being able to be saved empty

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](https://github.com/payloadcms/payload/tree/main/templates) directory (does not affect core functionality)
- [ ] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/payload/src/admin/components/forms/field-types/JSON/index.tsx [hunk 1]
```diff
@@ -71,10 +70,17 @@ const JSONField: React.FC<Props> = (props) => {
   )
 
   useEffect(() => {
-    if (hasLoadedValue) return
-    setStringValue(JSON.stringify(value ? value : initialValue, null, 2))
-    setHasLoadedValue(true)
-  }, [initialValue, value])
+    const hasValue = value && value.toString().length > 0
+    if (hasLoadedValue) {
+      setStringValue(hasValue ? JSON.stringify(value, null, 2) : '')
```
Comment (DanRibbens) [inline packages/payload/src/admin/components/forms/field-types/JSON/index.tsx:75]: Should this be in a `try` block also?
I'm assuming you are using `try/catch` to prevent errors from parsing and stringifying JSON.

Comment (JessChowdhury) [reply packages/payload/src/admin/components/forms/field-types/JSON/index.tsx]: Yes good call - updated!
