### PR TITLE
fix: updates syntax colors for light theme

### LINKED ISSUE #1425: Incorrect Theme for syntax higlight in light theme
# Bug Report

Dear dark-theme lovers, please don't forget about us, light theme lovers  😄

image

## Current Behavior

Code editor uses highlighting theme more suitable for dark-theme which mostly not readable on light theme.

### PR DESCRIPTION
**Pull request by JessRynkar**
## Description

Syntax colors are not suitable while using the Light theme - reported in [issue #1425](https://github.com/payloadcms/payload/issues/1425).

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] Existing test suite passes locally with my changes - test suite used: **Fields**

Screenshot below shows the updated colors:
Screen Shot 2022-11-28 at 4 26 22 PM

### CODE REVIEW

**Comment by edtorba** [comment]
It might be worth setting a different background colour too maybe? Even when in dark mode if the field is empty, you cannot tell where its boundaries start.

Screenshot 2022-11-28 at 21 54 09
^ On the top field I have manually set `var(--theme-elevation-50)` as a background colour.

Screenshot 2022-11-28 at 21 51 48
^ With some random code.

The same applies to the light theme.

**Comment by JarrodMFlesch** [comment]
I agree @edtorba, we can do that before merging this in.

**Comment by JessChowdhury** [comment]
@JarrodMFlesch I removed the theme provider and have added background / border to the input field (followed the same style as other fields).

@edtorba good call on the background - thank you!

Screen Shot 2022-11-29 at 10 46 56 AM
Screen Shot 2022-11-29 at 10 46 44 AM

File: src/admin/components/forms/field-types/Code/Code.tsx [hunk 1]
```diff
@@ -17,6 +17,7 @@ import Error from '../../Error';
 import FieldDescription from '../../FieldDescription';
 import { code } from '../../../../../fields/validations';
 import { Props } from './types';
+import { useTheme } from '../../../utilities/Theme';
```
Comment (JarrodMFlesch) [inline src/admin/components/forms/field-types/Code/Code.tsx:20]: I believe this can be removed.

File: src/admin/components/forms/field-types/Code/Code.tsx [hunk 2]
```diff
@@ -89,14 +90,13 @@ const Code: React.FC<Props> = (props) => {
         required={required}
       />
       <Editor
+        className="input"
```
Comment (JarrodMFlesch) [inline src/admin/components/forms/field-types/Code/Code.tsx:93]: Lets follow the current convention of using a `baseClass` and prepending that onto the elements className, see Array as an example here: https://github.com/payloadcms/payload/blob/master/src/admin/components/forms/field-types/Array/index.tsx#L31

**Review by JarrodMFlesch — CHANGES_REQUESTED** [review]

**Comment by JessChowdhury** [comment]
@JarrodMFlesch changes made

**Review by JarrodMFlesch — APPROVED** [review]
