### PR TITLE
fix: translate select field option labels

### LINKED ISSUE #1473: I18n options on select fields crashing page
# Bug Report

Found an issue with I18n Select using option labels in multiple languages making it unusable.

## Steps to Reproduce

Config:

1. Config collection with field: 
 ```ts
// ...
	{
      name: 'selectI18n',
      type: 'select',
      admin: {
        isClearable: true,
      },
      options: [
        {
          value: 'one',
          label: { en: 'One', es: 'Uno' },
        },
        {
          value: 'two',
          label: { en: 'Two', es: 'Dos' },
        },
        {
          value: 'three',
          label: { en: 'Three', es: 'Tres' },
        },
      ],
    },
```
2. Go to create collection
4. Use the select field to choose a value

UI crashes with error:
image

## Other Details

Payload v.1.2.0

WIP on fix!

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

https://github.com/payloadcms/payload/issues/1473

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: src/admin/components/forms/field-types/Select/Input.tsx [hunk 1]
```diff
@@ -62,9 +62,14 @@ const SelectInput: React.FC<SelectInputProps> = (props) => {
   let valueToRender;
 
   if (hasMany && Array.isArray(value)) {
-    valueToRender = value.map((val) => options.find((option) => option.value === val));
+    valueToRender = value.map((val) => {
+      const found = (options.find((option) => option.value === val));
+      found.label = getTranslation(found.label, i18n);
```
Comment (JarrodMFlesch) [inline src/admin/components/forms/field-types/Select/Input.tsx:67]: Do we want to ensure found exists before accessing found.label? Technically it could be undefined if not found.
