### PR TITLE
fix(cpa): updates CPAs w/ `vercel-postgres` db types to use `POSTGRES_URL` & updates `.env.example` to use generic env var strings

### LINKED ISSUE #9996: Inconsistent Environment Variable Naming in Payload CMS Setup for Vercel Postgres (DATABASE_URI vs. POSTGRES_URL)
### Describe the Bug

When creating a new project using `pnpx create-payload-app@latest` and select `Vercel Postgres` as database, the payload.config.ts file includes the following configuration:

```
db: vercelPostgresAdapter({
  pool: {
    connectionString: process.env.POSTGRES_URL || '',
  },
}),
```

However, the setup instructions provide DATABASE_URI as the environment variable for the database connection. This causes the following error during schema pulling:

```
[⣷] Pulling schema from database...
 ⨯ [Error: [object Object]] { digest: '24910920' }
```

The issue is resolved when changing the .env variable from DATABASE_URI to POSTGRES_URL, or by updating the payload.config.ts file to use process.env.DATABASE_URI.

Suggested Fix:
Update the default payload.config.ts to use:
```
connectionString: process.env.DATABASE_URI || '',
```
Or update the setup documentation to mention POSTGRES_URL as the expected environment variable.

### Link to the code that reproduces this issue

https://github.com/Montekkundan/payload-vercel

### Reproduction Steps

`pnpx create-payload-app@latest`

select `Vercel Postgres` as database

start with `pnpm dev`. `http://localhost:3000/` will not work until you change `env` variable in `payload.config.ts`

### Which area(s) are affected? (Select all that apply)

db-vercel-postgres

### Environment Info

```text
> payload-vercel@1.0.0 payload /Users/montekkundan/Developer/coding/payload-vercel
> cross-env NODE_OPTIONS=--no-deprecation payload "info"


Binaries:
  Node: 20.18.1
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.15.0
Relevant Packages:
  payload: 3.7.0
  next: 15.1.0
  @payloadcms/email-nodemailer: 3.7.0
  @payloadcms/graphql: 3.7.0
  @payloadcms/live-preview: 3.7.0
  @payloadcms/live-preview-react: 3.7.0
  @payloadcms/next/utilities: 3.7.0
  @payloadcms/payload-cloud: 3.7.0
  @payloadcms/plugin-form-builder: 3.7.0
  @payloadcms/plugin-nested-docs: 3.7.0
  @payloadcms/plugin-redirects: 3.7.0
  @payloadcms/plugin-search: 3.7.0
  @payloadcms/plugin-seo: 3.7.0
  @payloadcms/richtext-lexical: 3.7.0
  @payloadcms/translations: 3.7.0
  @payloadcms/ui/shared: 3.7.0
  react: 19.0.0
  react-dom: 19.0.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.2.0: Fri Dec  6 19:03:40 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6041
  Available memory (MB): 65536
  Available CPU cores: 16
```

### PR DESCRIPTION
**Pull request by PatrikKozak**
CPA projects generated with the `vercel-postgres` db type were not receiving the proper DB env vars in the .env.example & .env files

With the `vercel-postgres` db type, the DB env var needs to be `POSTGRES_URL` not `DATABASE_URI`.

Additionally, updates the generated .env.example file to show generic env var strings.

#### Blank w/ MongoDB:
- `.env.example`:
```
DATABASE_URI=mongodb://127.0.0.1/your-database-name
PAYLOAD_SECRET=YOUR_SECRET_HERE
```
- `.env`:
```
# Added by Payload
DATABASE_URI=mongodb://127.0.0.1/test-cpa-blank-mongodb
PAYLOAD_SECRET=aef857429edc7f42a90bb374
```

#### Blank w/ Postgres:
- `.env.example`:
```
DATABASE_URI=postgres://postgres:<password>@127.0.0.1:5432/your-database-name
PAYLOAD_SECRET=YOUR_SECRET_HERE
```
- `.env`:
```
# Added by Payload
DATABASE_URI=postgres://postgres:<password>@127.0.0.1:5432/test-cpa-blank-postgres
PAYLOAD_SECRET=241bfe11fbe0a56dd9757019
```

#### Blank w/ SQLite:
- `.env.example`:
```
DATABASE_URI=file:./your-database-name.db
PAYLOAD_SECRET=YOUR_SECRET_HERE
```
- `.env`:
```
# Added by Payload
DATABASE_URI=file:./test-cpa-blank-sqlite.db
PAYLOAD_SECRET=a7808731b93240a73a11930c
```

#### Blank w/ vercel-postgres:
- `.env.example`:
```
POSTGRES_URL=postgres://postgres:<password>@127.0.0.1:5432/your-database-name
PAYLOAD_SECRET=YOUR_SECRET_HERE
```
- `.env`:
```
# Added by Payload
POSTGRES_URL=postgres://postgres:<password>@127.0.0.1:5432/test-cpa-blank-vercel-postgres
PAYLOAD_SECRET=af3951e923e8e4662c9c3d9e
```

Fixes #9996

### CODE REVIEW

File: packages/create-payload-app/src/lib/manage-env-files.ts [hunk 1]
```diff
@@ -5,44 +5,68 @@ import type { CliArgs, DbType, ProjectTemplate } from '../types.js'
...
-        value = databaseUri
-        if (databaseType === 'vercel-postgres') {
-          value = databaseUri
+      const [key] = line.split('=')
+
+      // Handle placeholder connection strings based on databaseType
+      if (key === 'DATABASE_URI' || key === 'POSTGRES_URL' || key === 'MONGODB_URI') {
+        switch (databaseType) {
+          case 'mongodb':
+            return `DATABASE_URI=mongodb://your-connection-string-here`
```
Comment (denolfe) [inline packages/create-payload-app/src/lib/manage-env-files.ts:22]: All of these should be more realistic. Use `dbChoiceRecord`'s `dbConnectionPrefix` from `lib/select-db.ts`.

```
mongodb://127.0.0.1/payload-project
postgres://postgres:<password>@127.0.0.1:5432/payload-project
```

**Review by denolfe — CHANGES_REQUESTED** [review]
Add scope to PR title and one little adjustment needed.

File: packages/create-payload-app/src/lib/manage-env-files.ts (hunk 1 above)
Comment (PatrikKozak) [reply packages/create-payload-app/src/lib/manage-env-files.ts]: Done

**Review by denolfe — APPROVED** [review]
