### PR TITLE
fix(richtext-lexical): unnecessary `isEnabled` computations on toolbar items

### LINKED ISSUE #8170: Unnecessary `isEnabled` computations on Toolbar items
### Link to reproduction

_No response_

### Environment Info

```text
Payload: 3.0.0-beta.102
Next.js: 15.0.0-canary.104
Node.js: 20.17.0
```

### Describe the Bug

The `isEnabled` checks are fired a lot of times on irrelevant actions, such as scrolling the page, typing in a different Lexical instance, etc.

There is a property called `maxActiveItems` that aims to limit unnecessary computations, but it is not enough. One user has reported lag in his editor that he believes is due to this.

### Reproduction Steps

- Add a console.log in the useCallback called `updateStates` inside `packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.tsx`.
- Notice how the console.log is triggered lots of times on irrelevant actions, such as scrolling the page, typing in a different Lexical instance, etc.

### Adapters and Plugins

_No response_

### PR DESCRIPTION
**Pull request by GermanJablo**
Fixes #8170 

- wrapped onActiveChange in useCallback
- removed an unnecessary mouseUp event

Note: I put the console.log for debugging in the useCallback called updateStates inside packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.tsx.

## Before

https://github.com/user-attachments/assets/07d715d4-f6c7-4a4a-91ab-5de418c909d6

## After

https://github.com/user-attachments/assets/2d404d1c-d1a7-46fd-a5b6-7d01c5c16959

### CODE REVIEW

File: packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.tsx [hunk 1]
```diff
@@ -135,13 +135,6 @@ export const ToolbarDropdown = ({
     updateStates()
   }, [updateStates])
 
-  useEffect(() => {
-    document.addEventListener('mouseup', updateStates)
-    return () => {
-      document.removeEventListener('mouseup', updateStates)
-    }
-  }, [updateStates])
-
```
Comment (GermanJablo) [inline packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.tsx:144]: I think the reason this was done is to update the toolbar when the editor loses focus. Any other changes to the content selection are handled in the `registerUpdateListener` below.

A much less aggressive and sufficient event would be an onBlur on the editor container. We could add a Lexical `BLUR_COMMAND` and set the selection to null, but arguably this is Lexical's default behavior so I've opened an issue there: https://github.com/facebook/lexical/issues/6622

**Review by tylandavis — APPROVED** [review]
Looks good to me!

**Comment by denolfe** [comment]
🚀 This is included in version [v3.0.0-beta.105](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.105)
