### PR TITLE
fix(email-nodemailer): skipVerify behavior being reversed

### LINKED ISSUE #6789: Nodemailer Email Adapter: skipVerify=true does not skip verification
### Link to reproduction

_No response_

### Payload Version

3.0.0-beta.47

### Node Version

20.10.0

### Next.js Version

15.0.0-canary.29

### Describe the Bug

The `skipVerify` option of the `NodemailerAdapterArgs` has exactly the opposite effect.

`skipVerify: true` > Verifies the nodemailer transport
`skipVerify: false` > Does not verify the nodemailer transport

```ts
import { nodemailerAdapter } from "@payloadcms/email-nodemailer";
...
export default buildConfig({
...
  email: nodemailerAdapter({
      ...
      skipVerify: true,
      ...
  }),
...
}
```

### Reproduction Steps

1. Add the `@payloadcms/email-nodemailer `package to your Next.js/Payload project
2. Configure the adapter according to the docs [Nodemailer Email Adapter Docs](https://www.npmjs.com/package/@payloadcms/email-nodemailer?activeTab=readme)
3. Set the `skipVerify` option to `true`
4. Run/Build your Next.js/Payload project

Result: Nodemailer transporter.verify will be executed

### Adapters and Plugins

@payloadcms/email-nodemailer, nodemailer

### PR DESCRIPTION
**Pull request by JasperBeaurain**
## Description
Fixes #6789

The skipVerify field in NodemailerAdapterArgs worked in reverse of what it was supposed to do:
- With skipVerify = true -> Verified transport
- With skipVerify = false -> Did not verify transport

This PR makes the property work in the intended way:
- With skipVerify = true -> DO NOT verify transport
- With skipVerify = false -> DO verify transport

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/email-nodemailer/src/index.ts [hunk 1]
```diff
@@ -66,7 +66,7 @@ async function buildEmail(emailConfig?: NodemailerAdapterArgs): Promise<{
     transport = await createMockAccount(emailConfig)
   }
 
-  if (emailConfig.skipVerify !== false) {
+  if (emailConfig.skipVerify === false) {
```
Comment (denolfe) [inline packages/email-nodemailer/src/index.ts:69]: This also needs to handle when `skipVerify` is undefined. It should verify when undefined.

**Review by denolfe — CHANGES_REQUESTED** [review]
@JasperBeaurain Thanks for the PR! Just one additional scenario that needs to be handled.

**Comment by JasperBeaurain** [comment]
@denolfe Whoops, I missed that indeed. Made changes as requested.
I also added a few tests that validate the flag's behaviour.

**Comment by denolfe** [comment]
Thanks for the PR @JasperBeaurain ! Love that you added tests 🙏
