### PR TITLE
Fix/animated image uploads

### LINKED ISSUE #2181: images loosing animations
# Bug Report

Animated images, in gifs or webps are being processed as a single frame, sharp supports resizing and compressing these without loosing animations since v0.30.0.

It should be fairly straight forward to support this and I could take a stab later.

### PR DESCRIPTION
**Pull request by PatrikKozak**
## Description

Properly handles resizing of animated images with `animated` prop

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Existing test suite passes locally with my changes

### CODE REVIEW

File: src/uploads/generateFileData.ts [hunk 1]
```diff
@@ -71,6 +71,7 @@ export const generateFileData = async <T>({
   let newData = data;
   const filesToSave: FileToSave[] = [];
   const fileData: Partial<FileData> = {};
+  const fileIsAnimated = (file.mimetype === 'image/gif') || (file.mimetype === 'image/webp');
```
Comment (jacobsfletch) [inline src/uploads/generateFileData.ts:74]: Not all `webp` media will be animated, is there a way to target and omit these cases?

Comment (jmikrut) [reply src/uploads/generateFileData.ts:74]: nope, not easily... adding `animated: true` should not have any negative repercussions either so i think we're good 👍
