### PR TITLE
fix(ui): preserve localized blocks and arrays when using CopyToLocale

### LINKED ISSUE #12536: When copying or saving to a locale, the localized fields in arrays or blocks of other locales lose their values
### Describe the Bug

If a collection contains arrays or blocks with localized fields, copying one locale to another or simply saving the current locale causes other locales to lose their values. It seems that localized values are not merged but instead overwritten. I am using MongoDB, so I'm not sure if this behavior is different with relational databases

### Link to the code that reproduces this issue

https://github.com/epranka/payload-locales-save-issue

### Reproduction Steps

1. Clone the repository.
2. Run docker compose up and wait until both the app and MongoDB are ready.
3. Open http://localhost:3000/admin.
4. Create an account.
5. Create a new Page. Enter a title, add at least one item in an array or block with filled fields. In the Content tab, add any layout to avoid validation errors. Then, publish the page.
6. Click "Copy to locale" and select the "en" locale.
7. Switch back to the previous "lt" locale. You should see that the values in the array and block are lost.
8. Click "Copy to locale" and select the "lt" locale.
9. Switch back to the previous "en" locale. You should now see that the values are lost in that locale instead. Only the last saved locale retains its values.

### Which area(s) are affected? (Select all that apply)

Not sure

### Environment Info

```text
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: N/A
  pnpm: 10.11.0
Relevant Packages:
  payload: 3.39.1
  next: 15.3.0
  @payloadcms/db-mongodb: 3.39.1
  @payloadcms/email-nodemailer: 3.39.1
  @payloadcms/graphql: 3.39.1
  @payloadcms/live-preview: 3.39.1
  @payloadcms/live-preview-react: 3.39.1
  @payloadcms/next/utilities: 3.39.1
  @payloadcms/payload-cloud: 3.39.1
  @payloadcms/plugin-form-builder: 3.39.1
  @payloadcms/plugin-nested-docs: 3.39.1
  @payloadcms/plugin-redirects: 3.39.1
  @payloadcms/plugin-search: 3.39.1
  @payloadcms/plugin-seo: 3.39.1
  @payloadcms/richtext-lexical: 3.39.1
  @payloadcms/translations: 3.39.1
  @payloadcms/ui/shared: 3.39.1
  react: 19.1.0
  react-dom: 19.1.0
Operating System:
  Platform: linux
  Arch: x64
  Version: #61.1~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 18 12:20:24 UTC
  Available memory (MB): 64167
  Available CPU cores: 16
```

### PR DESCRIPTION
**Pull request by GermanJablo**
## Problem:
In PR #11887, a bug fix for `copyToLocale` was introduced to address issues with copying content between locales in Postgres. However, an incorrect algorithm was used, which removed all "id" properties from documents being copied. This led to bug #12536, where `copyToLocale` would mistakenly delete the document in the source language, affecting not only Postgres but any database.

## Cause and Solution:

When copying documents with localized arrays or blocks, Postgres throws errors if there are two blocks with the same ID. This is why PR #11887 removed all IDs from the document to avoid conflicts. However, this removal was too broad and caused issues in cases where it was unnecessary.

The correct solution should remove the IDs only in nested fields whose ancestors are localized. The reasoning is as follows:
- When an array/block is **not localized** (`localized: false`), if it contains localized fields, these fields share the same ID across different locales.
- When an array/block **is localized** (`localized: true`), its descendant fields cannot share the same ID across different locales if Postgres is being used. This wouldn't be an issue if the table containing localized blocks had a composite primary key of `locale + id`. However, since the primary key is just `id`, we need to assign a new ID for these fields.

This PR properly removes IDs **only for nested fields** whose ancestors are localized. 

Fixes #12536

### Before Fix:
```js
// Original document (en)
array: [{
  id: "123",
  text: { en: "English text" }
}]

// After copying to 'es' locale, a new ID was created instead of updating the existing item
array: [{
  id: "456",  // 🐛 New ID created!
  text: { es: "Spanish text" } // 🐛 'en' locale is missing
}]
```
### After fix:
```js
// After fix
array: [{
  id: "123",  // ✅ Same ID maintained
  text: {
    en: "English text",
    es: "Spanish text"  // ✅ Properly merged with existing item
  }
}]
```

### TraverseFields

In the process of designing an appropriate solution, I detected a couple of bugs in traverseFields that are also addressed in this PR.

### Fixed MongoDB Empty Array Handling

During testing, I discovered that MongoDB and PostgreSQL behave differently when querying documents that don't exist in a specific locale:
- PostgreSQL: Returns the document with data from the fallback locale
- MongoDB: Returns the document with empty arrays for localized fields

This difference caused `copyToLocale` to fail in MongoDB because the merge algorithm only checked for `null` or `undefined` values, but not empty arrays. When MongoDB returned `content: []` for a non-existent locale, the algorithm would attempt to iterate over the empty array instead of using the source locale's data.

### Move test e2e to int

The test introduced in #11887 didn't catch the bug because our e2e suite doesn't run on Postgres. I migrated the test to an integration test that does run on Postgres and MongoDB.

### CODE REVIEW

File: packages/payload/src/utilities/traverseFields.ts [hunk 1]
```diff
@@ -436,6 +448,7 @@ export const traverseFields = ({
             fillEmpty,
             leavesFirst,
             parentIsLocalized: parentIsLocalized!,
+            parentPath,
```
Comment (GermanJablo) [inline packages/payload/src/utilities/traverseFields.ts:451]: We were forgetting about forward `parentPath` here

File: packages/ui/src/utilities/copyDataFromLocale.ts [hunk 2]
```diff
@@ -70,8 +71,9 @@ function iterateFields(
           // if the field has no value, take the source value
           if (
             field.name in toLocaleData &&
-            // only replace if the target value is null or undefined
-            [null, undefined].includes(toLocaleData[field.name]) &&
+            // only replace if the target value is null, undefined, or empty array
+            ([null, undefined].includes(toLocaleData[field.name]) ||
+              (Array.isArray(toLocaleData[field.name]) && toLocaleData[field.name].length === 0)) &&
```
Comment (GermanJablo) [inline packages/ui/src/utilities/copyDataFromLocale.ts:76]: MongoDB and PostgreSQL behave differently when querying documents that don't exist in a specific locale:
- PostgreSQL: Returns the document with data from the fallback locale
- MongoDB: Returns the document with empty arrays for localized fields

This difference caused `copyToLocale` to fail in MongoDB because the merge algorithm only checked for `null` or `undefined` values, but not empty arrays. When MongoDB returned `content: []` for a non-existent locale, the algorithm would attempt to iterate over the empty array instead of using the source locale's data.

File: test/localization/e2e.spec.ts [hunk 3]
```diff
@@ -431,32 +431,6 @@ describe('Localization', () => {
...
-      await textField.fill(sampleText)
-      await saveDocAndAssert(page)
-
-      await openCopyToLocaleDrawer(page)
-      await setToLocale(page, 'English')
-      await runCopy(page)
-
-      await expect(textField).toHaveValue(sampleText)
-    })
-
```
Comment (GermanJablo) [inline test/localization/e2e.spec.ts:459]: This test was migrated to int. See comment below

File: test/localization/int.spec.ts [hunk 4]
```diff
@@ -2645,8 +2868,18 @@ describe('Localization', () => {
...
+
+        const refreshedDoc = await payload.findByID({
+          id: doc.id,
+          collection: 'nested',
+        })
+
+        // The source data should remain unchanged
+        expect(refreshedDoc.topLevelArray?.[0]?.localizedText).toBe('some-localized-text')
+        expect(refreshedDoc.topLevelArray?.[0]?.notLocalizedText).toBe('some-not-localized-text')
+        expect(refreshedDoc.topLevelArray).toHaveLength(1)
```
Comment (GermanJablo) [inline test/localization/int.spec.ts:2882]: I added this because this information was lost when doing copyToLocale

**Review by JarrodMFlesch — APPROVED** [review]
