### PR TITLE
fix: corrects keyboard accessibility for checkbox field

### LINKED ISSUE #2006: Checkbox field has two tab indexes
# Bug Report

## Steps to Reproduce

1. Create collection with text field and checkbox field and a second text field
2. Create new item and input some text in the text field
3. Press the `Tab` button on your keyboard
        - Expected: The checkbox is focused
        - Actual: There is no visible focus
3. Press the `Space` bar on your keyboard
        - Expected: The checkbox is checked
        - Actual: The checkbox remains unchecked
3. Press the `Tab` button on your keyboard again
        - Expected: The second input is focused
        - Actual: There is no visible focus. The checkbox can now be toggled using the spacebar though.
3. Press the `Tab` button on your keyboard again, the second input is now focused.

## Other Details

Payload 1.16

### PR DESCRIPTION
**Pull request by JessRynkar**
## Description

#2006 

Fixes double tab index on checkbox and adds focus highlight.

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

https://user-images.githubusercontent.com/67977755/217045001-552e4d04-4463-4168-8840-814e0f8292d2.mov

https://user-images.githubusercontent.com/67977755/217045004-0b6ca045-0b75-4b89-8283-42b938b16282.mov

### CODE REVIEW

File: src/admin/components/forms/field-types/Checkbox/Input.tsx [hunk 1]
```diff
@@ -43,9 +46,12 @@ export const CheckboxInput: React.FC<CheckboxInputProps> = (props) => {
         name={name}
         checked={checked}
         readOnly
+        tabIndex={-1}
```
Comment (JarrodMFlesch) [inline src/admin/components/forms/field-types/Checkbox/Input.tsx:49]: I believe you should just be able to use [aria-disabled](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled). Will need to test and verify.

File: src/admin/components/forms/field-types/Checkbox/Input.tsx [hunk 2]
```diff
@@ -43,9 +46,12 @@ export const CheckboxInput: React.FC<CheckboxInputProps> = (props) => {
...
       />
       <button
         type="button"
+        onFocus={() => setIsFocused(true)}
```
Comment (JarrodMFlesch) [inline src/admin/components/forms/field-types/Checkbox/Input.tsx:53]: Buttons already have the ability to be targeted when they are focused, we should use the css `:focus` to style this.

**Review by JarrodMFlesch — CHANGES_REQUESTED** [review]

**Comment by JessChowdhury** [comment]
@JarrodMFlesch changes made!
